const API = '/api/data';
const state = { data: { version:5, updatedAt:null, products:[], recipes:[], dietPlan:[], measurements:[], shoppingList:[] }, view:'dashboard', installPrompt:null, saving:false, productSearch:'' };
const $ = (s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>Number(v)||0; const fmt=v=>num(v).toLocaleString('pl-PL',{maximumFractionDigits:1});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function setStatus(text,bad=false){const e=$('#syncStatus');e.textContent=text;e.style.color=bad?'#a62929':''}
const COMMON_UNITS=['sztuka','kromka','szklanka','łyżka','łyżeczka','garść','plaster','opakowanie'];
const SHOP_CATEGORIES=['Warzywa i owoce','Mięso i ryby','Nabiał i jaja','Pieczywo i wypieki','Produkty zbożowe','Przetwory i suche produkty','Tłuszcze','Przyprawy i dodatki','Inne'];
const MEAL_TIME_SUGGESTIONS={
  'Śniadanie':'08:00',
  'II śniadanie':'11:00',
  'Obiad':'15:00',
  'Podwieczorek':'17:30',
  'Kolacja':'20:00',
  'Przekąska':'13:00',
  'Inne':'12:00'
};
function suggestedMealTime(mealType){return MEAL_TIME_SUGGESTIONS[mealType]||'12:00'}
function inferProductCategory(name=''){const n=String(name).toLowerCase();const rules=[
  ['Warzywa i owoce',['jabł','banan','grusz','pomidor','ogór','papryk','cukini','marchew','broku','szpinak','sałat','cebula','czosnek','pietrusz','seler','rzodk','winogron','grejpfrut','ananas','cytryn','fasolka szparag','roszpon','kapust']],
  ['Mięso i ryby',['kurcz','indyk','dorsz','łoso','tuńczy','wołow','wieprz','szynk','wędlin','mięso','ryba']],
  ['Nabiał i jaja',['mleko','jogurt','kefir','ser ','serek','twar','feta','mozzarell','parmezan','gouda','ricotta','jaj']],
  ['Pieczywo i wypieki',['chleb','bułk','pieczyw','tortill','wafl']],
  ['Produkty zbożowe',['płatki','ryż','makaron','kasza','kuskus','mąka','otręb','polenta']],
  ['Przetwory i suche produkty',['fasola','ciecierzyc','kukurydz','hummus','oliwk','pomidor suszon','żurawin','rodzyn','śliwk suszon','dżem','orzech','migdał','słonecznik','pestk','sezam','siemię']],
  ['Tłuszcze',['oliwa','olej','masło','awokado']],
  ['Przyprawy i dodatki',['sól','pieprz','cynamon','zioła','oregano','bazyl','curry','musztard','ocet','kakao','miód','czekolad','wiórki kokos','koperek','szczypior']]
];for(const [cat,words] of rules)if(words.some(w=>n.includes(w)))return cat;return 'Inne'}
function normalizeCategory(category,name='',inferLegacyOther=false){const value=String(category||'').trim();if(SHOP_CATEGORIES.includes(value)&&!(inferLegacyOther&&value==='Inne'))return value;return inferProductCategory(name)}
function normalizeProductUnits(p){const baseUnit=p.baseUnit==='ml'?'ml':'g';const conversions=(p.conversions&&typeof p.conversions==='object')?p.conversions:{};return {...p,baseUnit,conversions}}
function unitFactor(p,unit){if(!p)return 1;if(unit===p.baseUnit)return 1;if(unit==='kg'&&p.baseUnit==='g')return 1000;if(unit==='l'&&p.baseUnit==='ml')return 1000;return num(p.conversions?.[unit])||1}
function ingredientBaseAmount(i,p){if(i.baseAmount!=null)return num(i.baseAmount);if(i.grams!=null)return num(i.grams);return num(i.amount)*unitFactor(p,i.unit||p?.baseUnit||'g')}
function ingredientDisplay(i,p){const unit=i.unit||p?.baseUnit||'g';const amount=i.amount!=null?num(i.amount):(ingredientBaseAmount(i,p)/unitFactor(p,unit));return `${fmt(amount)} ${unit}`}
function availableUnits(p){if(!p)return ['g'];const units=[p.baseUnit];if(p.baseUnit==='g')units.push('kg');if(p.baseUnit==='ml')units.push('l');for(const u of COMMON_UNITS)if(num(p.conversions?.[u])>0)units.push(u);return [...new Set(units)]}
async function load(){setStatus('Pobieranie danych online…');try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);const r=await fetch(API,{cache:'no-store',signal:controller.signal});clearTimeout(timeout);const payload=await r.json().catch(()=>({}));if(!r.ok)throw Error(payload.error||`Błąd HTTP ${r.status}`);state.data=payload;state.data.shoppingList=Array.isArray(state.data.shoppingList)?state.data.shoppingList:[];const legacyVersion=num(state.data.version)<3;state.data.products=(state.data.products||[]).map(p=>normalizeProductUnits({...p,category:normalizeCategory(p.category,p.name,legacyVersion)}));state.data.shoppingList=state.data.shoppingList.map(x=>({...x,category:normalizeCategory(x.category,x.name,legacyVersion)}));state.data.dietPlan=(state.data.dietPlan||[]).map(m=>({...m,portions:Math.max(0.25,num(m.portions)||1)}));state.data.version=5;setStatus(state.data.updatedAt?`Zapisano: ${new Date(state.data.updatedAt).toLocaleString('pl-PL')}`:'Pusty plik danych – gotowe');render()}catch(e){setStatus(`Brak połączenia: ${e.message}`,true);toast('Nie udało się pobrać danych')}}
async function save(){if(state.saving)return;state.saving=true;setStatus('Zapisywanie do JSON…');try{const r=await fetch(API,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state.data)});const body=await r.json();if(!r.ok)throw Error(body.error);state.data=body;setStatus(`Zapisano: ${new Date(body.updatedAt).toLocaleString('pl-PL')}`);toast('Dane zapisane online')}catch(e){setStatus(`Błąd zapisu: ${e.message}`,true);toast('Błąd zapisu')}finally{state.saving=false;render()}}
function go(view){state.view=view;$$('.view').forEach(e=>e.classList.toggle('active',e.id===view));$$('.tabs button').forEach(e=>e.classList.toggle('active',e.dataset.view===view));renderView(view)}
function render(){renderView(state.view)}
function renderView(v){({dashboard:renderDashboard,products:renderProducts,recipes:renderRecipes,plan:renderPlan,shopping:renderShopping,measurements:renderMeasurements,settings:renderSettings}[v]||renderDashboard)()}
function head(title,action,label='Dodaj'){return `<div class="section-head"><h2>${title}</h2>${action?`<button class="primary" data-action="${action}">+ ${label}</button>`:''}</div>`}
function empty(t){return `<div class="empty">${t}</div>`}
function productById(id){return state.data.products.find(x=>x.id===id)} function recipeById(id){return state.data.recipes.find(x=>x.id===id)}
function recipeNutrition(r){return (r.ingredients||[]).reduce((a,i)=>{const p=productById(i.productId);const q=ingredientBaseAmount(i,p)/100;if(p){a.kcal+=num(p.kcal)*q;a.protein+=num(p.protein)*q;a.fat+=num(p.fat)*q;a.carbs+=num(p.carbs)*q}return a},{kcal:0,protein:0,fat:0,carbs:0})}
function mealsNutrition(meals=[]){return meals.reduce((a,m)=>{const r=recipeById(m.recipeId);if(r){const n=recipeNutrition(r),portions=Math.max(0.25,num(m.portions)||1);a.kcal+=n.kcal*portions;a.protein+=n.protein*portions;a.fat+=n.fat*portions;a.carbs+=n.carbs*portions}return a},{kcal:0,protein:0,fat:0,carbs:0})}
function daySummaryHtml(meals=[]){const n=mealsNutrition(meals);return `<div class="day-summary"><div><strong>${fmt(n.kcal)}</strong><span>kcal</span></div><div><strong>${fmt(n.protein)} g</strong><span>białko</span></div><div><strong>${fmt(n.fat)} g</strong><span>tłuszcz</span></div><div><strong>${fmt(n.carbs)} g</strong><span>węglowodany</span></div></div>`}
function renderDashboard(){const d=state.data;const latest=[...d.measurements].sort((a,b)=>b.date.localeCompare(a.date))[0];const today=new Date().toISOString().slice(0,10);const meals=d.dietPlan.filter(x=>x.date===today).sort((a,b)=>(a.time||'').localeCompare(b.time||''));$('#dashboard').innerHTML=`${head('Podsumowanie')}<div class="cards"><div class="card stat"><strong>${d.products.length}</strong><span>produktów</span></div><div class="card stat"><strong>${d.recipes.length}</strong><span>przepisów</span></div><div class="card stat"><strong>${d.dietPlan.length}</strong><span>pozycji planu</span></div><div class="card stat"><strong>${(d.shoppingList||[]).filter(x=>!x.purchased).length}</strong><span>do kupienia</span></div><div class="card stat"><strong>${latest?fmt(latest.weight)+' kg':'—'}</strong><span>ostatnia masa</span></div></div><div style="height:14px"></div><div class="grid"><div class="panel"><h3>Dzisiejszy plan</h3>${meals.length?daySummaryHtml(meals)+meals.map(mealHtml).join(''):empty('Brak posiłków na dziś.')}</div><div class="panel"><h3>Szybki start</h3><p>Dodaj produkty, utwórz przepisy, a następnie przypisz je do dni i typów posiłków.</p><button class="primary" data-nav="products">Dodaj produkt</button> <button class="secondary" data-nav="recipes">Dodaj przepis</button></div></div>`}
function renderProducts(){const q=(state.productSearch||'').trim().toLowerCase();const list=state.data.products.filter(p=>p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));$('#products').innerHTML=`${head('Produkty','add-product')}<div class="toolbar search-toolbar"><input id="productSearch" type="search" autocomplete="off" placeholder="Szukaj po nazwie lub kategorii…" value="${esc(state.productSearch)}"><button type="button" class="secondary ${state.productSearch?'':'hidden'}" id="clearProductSearch">Wyczyść</button></div><div class="search-result-info">${q?`Znaleziono: ${list.length}`:`Wszystkie produkty: ${list.length}`}</div><div class="list">${list.length?list.map(p=>`<article class="item"><div><h3>${esc(p.name)}</h3><p>${esc(p.category||'Inne')} · ${fmt(p.kcal)} kcal · B ${fmt(p.protein)} g · T ${fmt(p.fat)} g · W ${fmt(p.carbs)} g / 100 ${esc(p.baseUnit||'g')}</p></div><div class="item-actions"><button class="icon-btn" data-edit-product="${p.id}" title="Edytuj">✎</button><button class="icon-btn danger" data-delete-product="${p.id}" title="Usuń">×</button></div></article>`).join(''):empty(q?'Brak produktów pasujących do wyszukiwania.':'Nie ma jeszcze produktów.')}</div>`;const input=$('#productSearch');input?.addEventListener('input',e=>{state.productSearch=e.target.value;renderProducts();const next=$('#productSearch');if(next){next.focus();next.setSelectionRange(next.value.length,next.value.length)}});$('#clearProductSearch')?.addEventListener('click',()=>{state.productSearch='';renderProducts();$('#productSearch')?.focus()})}
function recipeDetailsHtml(r,multiplier=1){if(!r)return '';const portions=Math.max(0.25,num(multiplier)||1),n=recipeNutrition(r);const ingredients=(r.ingredients||[]).map(i=>{const p=productById(i.productId);const unit=i.unit||p?.baseUnit||'g';const amount=(i.amount!=null?num(i.amount):(ingredientBaseAmount(i,p)/unitFactor(p,unit)))*portions;return `<li><span>${esc(p?.name||'Nieznany produkt')}</span><strong>${fmt(amount)} ${esc(unit)}</strong></li>`}).join('');return `<details class="recipe-details"><summary>Pokaż szczegóły przepisu</summary><div class="recipe-details-content"><div class="recipe-nutrition"><span>${fmt(n.kcal*portions)} kcal</span><span>B ${fmt(n.protein*portions)} g</span><span>T ${fmt(n.fat*portions)} g</span><span>W ${fmt(n.carbs*portions)} g</span></div><div><h4>Składniki${portions!==1?` dla ${fmt(portions)} porcji`:''}</h4>${ingredients?`<ul class="ingredient-list">${ingredients}</ul>`:'<p>Brak składników.</p>'}</div><div><h4>Sposób przygotowania</h4><p class="instructions">${r.instructions?esc(r.instructions).replace(/\n/g,'<br>'):'Brak opisu przygotowania.'}</p></div></div></details>`}
function renderRecipes(){const list=[...state.data.recipes].sort((a,b)=>a.name.localeCompare(b.name));$('#recipes').innerHTML=`${head('Przepisy','add-recipe')}<div class="list">${list.length?list.map(r=>{const n=recipeNutrition(r);return `<article class="item recipe-card"><div class="item-main"><span class="badge">${esc(r.mealType||'Inne')}</span><h3>${esc(r.name)}</h3><p>${fmt(n.kcal)} kcal · B ${fmt(n.protein)} g · T ${fmt(n.fat)} g · W ${fmt(n.carbs)} g</p><p>${(r.ingredients||[]).length} składników</p>${recipeDetailsHtml(r)}</div><div class="item-actions"><button class="icon-btn" data-edit-recipe="${r.id}">✎</button><button class="icon-btn danger" data-delete-recipe="${r.id}">×</button></div></article>`}).join(''):empty('Nie ma jeszcze przepisów.')}</div>`}
function mealHtml(m){const r=recipeById(m.recipeId),portions=Math.max(0.25,num(m.portions)||1);return `<div class="item meal-card"><div class="item-main"><span class="badge">${esc(m.mealType||'Posiłek')}</span><h3>${esc(m.time||'')} ${esc(r?.name||m.customName||'Brak przepisu')}</h3><p class="meal-portions">${fmt(portions)} ${portions===1?'porcja':'porcje'}</p>${r?recipeDetailsHtml(r,portions):'<p>Przepis nie jest już dostępny.</p>'}</div><div class="item-actions"><button class="icon-btn" data-edit-meal="${m.id}">✎</button><button class="icon-btn danger" data-delete-meal="${m.id}">×</button></div></div>`}
function renderPlan(){const list=[...state.data.dietPlan].sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||''));const groups=Object.groupBy?Object.groupBy(list,x=>x.date):list.reduce((a,x)=>((a[x.date]??=[]).push(x),a),{});$('#plan').innerHTML=`${head('Plan diety','add-meal')}<div class="list">${Object.keys(groups).length?Object.entries(groups).map(([date,items])=>`<div class="panel day-panel"><div class="day-heading"><h3>${new Date(date+'T12:00:00').toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</h3><span>${items.length} ${items.length===1?'posiłek':'posiłki'}</span></div>${daySummaryHtml(items)}${items.map(mealHtml).join('')}</div>`).join(''):empty('Plan diety jest pusty.')}</div>`}
function shoppingGroups(){const items=[...(state.data.shoppingList||[])].sort((a,b)=>(a.purchased-b.purchased)||(a.category||'Inne').localeCompare(b.category||'Inne')||a.name.localeCompare(b.name));return items.reduce((g,x)=>((g[x.category||'Inne']??=[]).push(x),g),{})}
function renderShopping(){const items=state.data.shoppingList||[];const groups=shoppingGroups();const bought=items.filter(x=>x.purchased).length;const today=new Date().toISOString().slice(0,10);const end=new Date(Date.now()+6*86400000).toISOString().slice(0,10);$('#shopping').innerHTML=`${head('Koszyk zakupowy','add-shopping','Dodaj pozycję')}<div class="panel shopping-generator"><h3>Generuj z planu diety</h3><div class="form-grid"><label>Od daty<input id="shoppingFrom" type="date" value="${today}"></label><label>Do daty<input id="shoppingTo" type="date" value="${end}"></label></div><div class="form-actions"><button class="secondary" data-action="clear-purchased">Usuń kupione</button><button class="primary" data-action="generate-shopping">Generuj listę</button></div></div><div class="shopping-summary"><span>${items.length} pozycji</span><span>${bought} kupionych</span><span>${items.length-bought} do kupienia</span></div><div class="shopping-sections">${Object.keys(groups).length?Object.entries(groups).map(([cat,list])=>`<section class="panel shopping-category"><h3>${esc(cat)}</h3><div class="shopping-table">${list.map(x=>`<div class="shopping-row ${x.purchased?'purchased':''}"><label class="shopping-check"><input type="checkbox" data-toggle-shopping="${x.id}" ${x.purchased?'checked':''}><span></span></label><div class="shopping-name"><strong>${esc(x.name)}</strong><small>${fmt(x.amount)} ${esc(x.unit||'g')}${x.source==='plan'?' · z planu':''}</small></div><div class="item-actions"><button class="icon-btn" data-edit-shopping="${x.id}">✎</button><button class="icon-btn danger" data-delete-shopping="${x.id}">×</button></div></div>`).join('')}</div></section>`).join(''):empty('Koszyk jest pusty. Wygeneruj listę z planu albo dodaj pozycję ręcznie.')}</div>`}
function generateShopping(){const from=$('#shoppingFrom')?.value,to=$('#shoppingTo')?.value;if(!from||!to)return toast('Wybierz zakres dat');if(from>to)return toast('Data początkowa jest późniejsza niż końcowa');const totals=new Map();state.data.dietPlan.filter(m=>m.date>=from&&m.date<=to).forEach(m=>{const r=recipeById(m.recipeId);(r?.ingredients||[]).forEach(i=>{const p=productById(i.productId);if(!p)return;const key=p.id;const prev=totals.get(key)||{id:uid(),productId:p.id,name:p.name,amount:0,unit:'g',category:normalizeCategory(p.category,p.name),purchased:false,source:'plan'};prev.amount+=ingredientBaseAmount(i,p)*Math.max(0.25,num(m.portions)||1);prev.unit=p.baseUnit||'g';totals.set(key,prev)})});const manual=(state.data.shoppingList||[]).filter(x=>x.source!=='plan');state.data.shoppingList=[...manual,...totals.values()];save()}
function shoppingForm(item){openModal(item?'Edytuj pozycję':'Dodaj do koszyka',`<div class="form-grid"><label class="full">Nazwa<input name="name" required value="${esc(item?.name||'')}"></label><label>Ilość<input name="amount" type="number" step="0.1" min="0" required value="${item?.amount??''}"></label><label>Jednostka<select name="unit">${['g','kg','ml','l','szt.','opak.'].map(x=>`<option ${item?.unit===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Kategoria<select name="category">${SHOP_CATEGORIES.map(x=>`<option ${item?.category===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const x={id:item?.id||uid(),productId:item?.productId||'',name:fd.get('name').trim(),amount:num(fd.get('amount')),unit:fd.get('unit'),category:fd.get('category'),purchased:item?.purchased||false,source:item?.source||'manual'};item?Object.assign(item,x):state.data.shoppingList.push(x);closeModal();await save()})}

function renderMeasurements(){const list=[...state.data.measurements].sort((a,b)=>b.date.localeCompare(a.date));$('#measurements').innerHTML=`${head('Pomiary','add-measurement')}<div class="list">${list.length?list.map(m=>`<article class="item"><div><h3>${new Date(m.date+'T12:00:00').toLocaleDateString('pl-PL')}</h3><p>Masa: <b>${m.weight?fmt(m.weight)+' kg':'—'}</b> · Talia: ${m.waist?fmt(m.waist)+' cm':'—'} · Klatka: ${m.chest?fmt(m.chest)+' cm':'—'}</p>${m.notes?`<p>${esc(m.notes)}</p>`:''}</div><div class="item-actions"><button class="icon-btn" data-edit-measurement="${m.id}">✎</button><button class="icon-btn danger" data-delete-measurement="${m.id}">×</button></div></article>`).join(''):empty('Nie ma jeszcze pomiarów.')}</div>`}
function renderSettings(){const size=new Blob([JSON.stringify(state.data)]).size;$('#settings').innerHTML=`${head('Dane i kopie bezpieczeństwa')}<div class="settings-grid"><div class="panel"><h3>Excel</h3><p>Eksport zawiera osobne arkusze: Produkty, Przepisy, Skladniki, Plan_diety, Lista_zakupow i Pomiary.</p><button class="primary" data-action="export-excel">Eksportuj Excel</button><label class="file-label" style="margin-top:10px">Importuj Excel<input type="file" id="excelImport" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel"></label><p class="hint">Najbezpieczniej edytować plik wcześniej wyeksportowany z aplikacji. Import zastępuje wszystkie dane.</p></div><div class="panel"><h3>Plik online</h3><p>Dane są przechowywane jako jeden plik <code>diet-data.json</code> w Vercel Blob.</p><p>Rozmiar: ${fmt(size/1024)} KB</p><button class="secondary" data-action="export-json">Eksportuj JSON</button><label class="file-label" style="margin-top:10px">Importuj JSON<input type="file" id="jsonImport" accept="application/json,.json"></label></div><div class="panel"><h3>Przykładowe dane</h3><p>Dodaj kilka produktów i przepisów, aby szybko sprawdzić aplikację.</p><button class="secondary" data-action="seed">Dodaj dane demonstracyjne</button></div><div class="panel"><h3>Usuń wszystko</h3><p>Operacja zapisze pusty plik JSON online.</p><button class="danger-btn" data-action="clear-all">Wyczyść dane</button></div></div>`}
function openModal(title,html,onSubmit){$('#modalTitle').textContent=title;const f=$('#modalForm');f.innerHTML=html;f.onsubmit=e=>{e.preventDefault();onSubmit(new FormData(f))};$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');$('#modalForm').innerHTML=''}

function ensureXlsx(){if(!window.XLSX){toast('Nie udało się załadować obsługi Excel');throw Error('Biblioteka Excel jest niedostępna')}return window.XLSX}
function sheetFromRows(rows,widths=[]){const X=ensureXlsx();const ws=X.utils.json_to_sheet(rows);if(widths.length)ws['!cols']=widths.map(w=>({wch:w}));return ws}
function exportExcel(){
  const X=ensureXlsx();
  const wb=X.utils.book_new();
  const products=state.data.products.map(p=>({ID:p.id,Nazwa:p.name,Kategoria:p.category||'Inne',Jednostka_bazowa:p.baseUnit||'g',Przeliczniki_JSON:JSON.stringify(p.conversions||{}),Kalorie_100g:num(p.kcal),Bialko_100g:num(p.protein),Tluszcz_100g:num(p.fat),Weglowodany_100g:num(p.carbs)}));
  const recipes=state.data.recipes.map(r=>({ID:r.id,Nazwa:r.name,Typ_posilku:r.mealType||'',Przygotowanie:r.instructions||''}));
  const ingredients=state.data.recipes.flatMap(r=>(r.ingredients||[]).map(i=>{const p=productById(i.productId);return {ID_przepisu:r.id,Nazwa_przepisu:r.name,ID_produktu:i.productId,Nazwa_produktu:p?.name||'',Ilosc:num(i.amount??ingredientBaseAmount(i,p)),Jednostka:i.unit||p?.baseUnit||'g',Ilosc_bazowa:ingredientBaseAmount(i,p)}}));
  const plan=state.data.dietPlan.map(m=>{const r=recipeById(m.recipeId);return {ID:m.id,Data:m.date,Godzina:m.time||'',Typ_posilku:m.mealType||'',ID_przepisu:m.recipeId,Nazwa_przepisu:r?.name||'',Liczba_porcji:Math.max(0.25,num(m.portions)||1)}});
  const shopping=(state.data.shoppingList||[]).map(x=>({ID:x.id,Nazwa:x.name,Ilosc:num(x.amount),Jednostka:x.unit||'g',Kategoria:x.category||'Inne',Kupione:x.purchased?'TAK':'NIE',Zrodlo:x.source||'manual'}));
  const measurements=state.data.measurements.map(m=>({ID:m.id,Data:m.date,Masa_kg:m.weight??'',Talia_cm:m.waist??'',Klatka_cm:m.chest??'',Notatki:m.notes||''}));
  X.utils.book_append_sheet(wb,sheetFromRows(products,[38,28,26,14,14,14,19]),'Produkty');
  X.utils.book_append_sheet(wb,sheetFromRows(recipes,[38,30,18,60]),'Przepisy');
  X.utils.book_append_sheet(wb,sheetFromRows(ingredients,[38,30,38,28,12]),'Skladniki');
  X.utils.book_append_sheet(wb,sheetFromRows(plan,[38,14,10,18,38,30]),'Plan_diety');
  X.utils.book_append_sheet(wb,sheetFromRows(shopping,[38,28,12,12,26,10,12]),'Lista_zakupow');
  X.utils.book_append_sheet(wb,sheetFromRows(measurements,[38,14,12,12,12,45]),'Pomiary');
  X.writeFile(wb,`moja-dieta-${new Date().toISOString().slice(0,10)}.xlsx`);
}
function rowsFromSheet(wb,name){const X=ensureXlsx();const ws=wb.Sheets[name];return ws?X.utils.sheet_to_json(ws,{defval:'',raw:false}):[]}
function cell(row,...names){for(const n of names){if(row[n]!==undefined&&row[n]!==null&&String(row[n]).trim()!=='')return row[n]}return ''}
function excelNumber(v){if(v===''||v===null||v===undefined)return 0;return Number(String(v).replace(',','.'))||0}
function excelDate(v){if(!v)return '';const text=String(v).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;const m=text.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(text);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
async function importExcel(file){
  const X=ensureXlsx();const wb=X.read(await file.arrayBuffer(),{type:'array',cellDates:true});
  const productRows=rowsFromSheet(wb,'Produkty'),recipeRows=rowsFromSheet(wb,'Przepisy'),ingredientRows=rowsFromSheet(wb,'Skladniki'),planRows=rowsFromSheet(wb,'Plan_diety'),shoppingRows=rowsFromSheet(wb,'Lista_zakupow'),measurementRows=rowsFromSheet(wb,'Pomiary');
  if(!productRows.length&&!recipeRows.length&&!planRows.length&&!measurementRows.length)throw Error('Brak obsługiwanych arkuszy');
  const products=productRows.filter(r=>String(cell(r,'Nazwa','Produkt')).trim()).map(r=>({id:String(cell(r,'ID')||uid()),name:String(cell(r,'Nazwa','Produkt')).trim(),kcal:excelNumber(cell(r,'Kalorie_100g','Kalorie','kcal')),protein:excelNumber(cell(r,'Bialko_100g','Bialko')),fat:excelNumber(cell(r,'Tluszcz_100g','Tluszcz')),carbs:excelNumber(cell(r,'Weglowodany_100g','Weglowodany')),category:normalizeCategory(String(cell(r,'Kategoria')||'').trim(),String(cell(r,'Nazwa','Produkt')).trim(),true),baseUnit:String(cell(r,'Jednostka_bazowa')||'g')==='ml'?'ml':'g',conversions:(()=>{try{return JSON.parse(String(cell(r,'Przeliczniki_JSON')||'{}'))}catch{return {}}})()}));
  const productByExcelId=new Map(products.map(p=>[p.id,p]));const productByName=new Map(products.map(p=>[p.name.toLowerCase(),p]));
  const recipes=recipeRows.filter(r=>String(cell(r,'Nazwa','Przepis')).trim()).map(r=>({id:String(cell(r,'ID')||uid()),name:String(cell(r,'Nazwa','Przepis')).trim(),mealType:String(cell(r,'Typ_posilku','Typ posilku')||'Inne').trim(),instructions:String(cell(r,'Przygotowanie','Sposob przygotowania')||'').trim(),ingredients:[]}));
  const recipeByExcelId=new Map(recipes.map(r=>[r.id,r]));const recipeByName=new Map(recipes.map(r=>[r.name.toLowerCase(),r]));
  for(const row of ingredientRows){const recipe=recipeByExcelId.get(String(cell(row,'ID_przepisu')))||recipeByName.get(String(cell(row,'Nazwa_przepisu')).trim().toLowerCase());const product=productByExcelId.get(String(cell(row,'ID_produktu')))||productByName.get(String(cell(row,'Nazwa_produktu')).trim().toLowerCase());const amount=excelNumber(cell(row,'Ilosc','Ilosc_g'));const unit=String(cell(row,'Jednostka')||product?.baseUnit||'g');const baseAmount=excelNumber(cell(row,'Ilosc_bazowa'))||amount*unitFactor(product,unit);if(recipe&&product&&amount>0)recipe.ingredients.push({productId:product.id,amount,unit,baseAmount,grams:baseAmount})}
  const dietPlan=planRows.filter(r=>excelDate(cell(r,'Data'))).map(r=>{const recipe=recipeByExcelId.get(String(cell(r,'ID_przepisu')))||recipeByName.get(String(cell(r,'Nazwa_przepisu')).trim().toLowerCase());return {id:String(cell(r,'ID')||uid()),date:excelDate(cell(r,'Data')),time:String(cell(r,'Godzina')||''),mealType:String(cell(r,'Typ_posilku','Typ posilku')||recipe?.mealType||'Inne'),recipeId:recipe?.id||'',portions:Math.max(0.25,excelNumber(cell(r,'Liczba_porcji','Porcje'))||1)}}).filter(x=>x.recipeId);
  const shoppingList=shoppingRows.filter(r=>String(cell(r,'Nazwa')).trim()).map(r=>({id:String(cell(r,'ID')||uid()),productId:'',name:String(cell(r,'Nazwa')).trim(),amount:excelNumber(cell(r,'Ilosc')),unit:String(cell(r,'Jednostka')||'g'),category:normalizeCategory(String(cell(r,'Kategoria')||'').trim(),String(cell(r,'Nazwa')).trim(),true),purchased:String(cell(r,'Kupione')).toUpperCase()==='TAK',source:String(cell(r,'Zrodlo')||'manual')}));
  const measurements=measurementRows.filter(r=>excelDate(cell(r,'Data'))).map(r=>({id:String(cell(r,'ID')||uid()),date:excelDate(cell(r,'Data')),weight:excelNumber(cell(r,'Masa_kg','Masa'))||null,waist:excelNumber(cell(r,'Talia_cm','Talia'))||null,chest:excelNumber(cell(r,'Klatka_cm','Klatka'))||null,notes:String(cell(r,'Notatki')||'').trim()}));
  if(!confirm(`Zaimportować dane z Excela?\nProdukty: ${products.length}\nPrzepisy: ${recipes.length}\nPlan: ${dietPlan.length}\nKoszyk: ${shoppingList.length}\nPomiary: ${measurements.length}\n\nAktualne dane zostaną zastąpione.`))return;
  state.data={version:5,updatedAt:null,products,recipes,dietPlan,measurements,shoppingList};await save();toast('Dane z Excela zostały zaimportowane');
}

const actions={
'add-product':()=>productForm(), 'add-recipe':()=>recipeForm(), 'add-meal':()=>mealForm(), 'add-shopping':()=>shoppingForm(), 'add-measurement':()=>measurementForm(),
'generate-shopping':()=>generateShopping(), 'clear-purchased':async()=>{state.data.shoppingList=(state.data.shoppingList||[]).filter(x=>!x.purchased);await save()},
'export-excel':()=>exportExcel(),
'export-json':()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}));a.download=`moja-dieta-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)},
'seed':async()=>{if(state.data.products.length&&!confirm('Dodać dane demonstracyjne do istniejących danych?'))return;const p1={id:uid(),name:'Płatki owsiane',category:'Produkty zbożowe',kcal:370,protein:13,fat:7,carbs:60,baseUnit:'g',conversions:{'szklanka':90,'łyżka':10}},p2={id:uid(),name:'Banan',category:'Warzywa i owoce',kcal:89,protein:1.1,fat:.3,carbs:23,baseUnit:'g',conversions:{'sztuka':120}},p3={id:uid(),name:'Migdały',category:'Przetwory i suche produkty',kcal:579,protein:21,fat:50,carbs:22,baseUnit:'g',conversions:{'łyżka':15,'garść':25}};state.data.products.push(p1,p2,p3);state.data.recipes.push({id:uid(),name:'Owsianka z bananem i migdałami',mealType:'Śniadanie',instructions:'Płatki zalej gorącą wodą. Dodaj banana i posiekane migdały.',ingredients:[{productId:p1.id,amount:60,unit:'g',baseAmount:60,grams:60},{productId:p2.id,amount:1,unit:'sztuka',baseAmount:120,grams:120},{productId:p3.id,amount:20,unit:'g',baseAmount:20,grams:20}]});await save()},
'clear-all':async()=>{if(confirm('Usunąć wszystkie produkty, przepisy, plany, koszyk i pomiary?')){state.data={version:5,updatedAt:null,products:[],recipes:[],dietPlan:[],measurements:[],shoppingList:[]};await save()}}
};
function conversionFields(p={}){return COMMON_UNITS.map(u=>`<label>${u} = ile ${p.baseUnit||'g'}?<input name="conv_${u}" type="number" min="0" step="0.1" value="${p.conversions?.[u]??''}" placeholder="opcjonalnie"></label>`).join('')}
function fieldsProduct(p={}){p=normalizeProductUnits(p);return `<div class="form-grid"><label class="full">Nazwa<input name="name" required value="${esc(p.name||'')}"></label><label>Kategoria<select name="category">${SHOP_CATEGORIES.map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Jednostka bazowa<select name="baseUnit" id="baseUnit"><option value="g" ${p.baseUnit==='g'?'selected':''}>g</option><option value="ml" ${p.baseUnit==='ml'?'selected':''}>ml</option></select></label><label>Kalorie / 100 jednostek<input name="kcal" type="number" step="0.1" min="0" value="${p.kcal??''}"></label><label>Białko / 100<input name="protein" type="number" step="0.1" min="0" value="${p.protein??''}"></label><label>Tłuszcz / 100<input name="fat" type="number" step="0.1" min="0" value="${p.fat??''}"></label><label>Węglowodany / 100<input name="carbs" type="number" step="0.1" min="0" value="${p.carbs??''}"></label><div class="full"><h4>Jednostki domowe</h4><p class="hint">Wpisz, ile gramów lub mililitrów odpowiada jednej jednostce. Puste pola nie będą dostępne w przepisach.</p><div class="form-grid">${conversionFields(p)}</div></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`}
function productForm(p){openModal(p?'Edytuj produkt':'Dodaj produkt',fieldsProduct(p),async fd=>{const conversions={};for(const u of COMMON_UNITS){const v=num(fd.get(`conv_${u}`));if(v>0)conversions[u]=v}const x={id:p?.id||uid(),name:fd.get('name').trim(),kcal:num(fd.get('kcal')),protein:num(fd.get('protein')),fat:num(fd.get('fat')),carbs:num(fd.get('carbs')),category:normalizeCategory(fd.get('category'),fd.get('name')),baseUnit:fd.get('baseUnit')==='ml'?'ml':'g',conversions};p?Object.assign(p,x):state.data.products.push(x);closeModal();await save()})}
function recipeForm(r){const ingredients=r?.ingredients?.length?r.ingredients:[{productId:'',amount:'',unit:'g'}];const rows=ingredients.map((i,idx)=>ingredientRow(i,idx)).join('');openModal(r?'Edytuj przepis':'Dodaj przepis',`<div class="form-grid"><label class="full">Nazwa<input name="name" required value="${esc(r?.name||'')}"></label><label>Typ posiłku<select name="mealType">${['Śniadanie','II śniadanie','Obiad','Podwieczorek','Kolacja','Przekąska','Inne'].map(x=>`<option ${r?.mealType===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Sposób przygotowania<textarea name="instructions">${esc(r?.instructions||'')}</textarea></label><div class="full"><b>Składniki</b><div id="ingredientRows" class="list" style="margin-top:8px">${rows}</div><button type="button" class="secondary" id="addIngredient">+ Składnik</button></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const productIds=fd.getAll('productId'),amounts=fd.getAll('ingredientAmount'),units=fd.getAll('ingredientUnit');const ingredients=productIds.map((id,i)=>{const p=productById(id),amount=num(amounts[i]),unit=units[i]||p?.baseUnit||'g',baseAmount=amount*unitFactor(p,unit);return {productId:id,amount,unit,baseAmount,grams:baseAmount}}).filter(i=>i.productId&&i.amount>0);const x={id:r?.id||uid(),name:fd.get('name').trim(),mealType:fd.get('mealType'),instructions:fd.get('instructions').trim(),ingredients};r?Object.assign(r,x):state.data.recipes.push(x);closeModal();await save()});$('#addIngredient').onclick=()=>$('#ingredientRows').insertAdjacentHTML('beforeend',ingredientRow({},Date.now()))}
function productOptions(selectedId='',query=''){const q=(query||'').trim().toLowerCase();return [...state.data.products].filter(p=>!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${p.id}" ${selectedId===p.id?'selected':''}>${esc(p.name)} — ${esc(p.category||'Inne')}</option>`).join('')}
function unitOptions(p,selected=''){return availableUnits(p).map(u=>`<option value="${esc(u)}" ${selected===u?'selected':''}>${esc(u)}</option>`).join('')}
function ingredientRow(i,idx){const selectId=`ingredient-product-${idx}-${Math.random().toString(36).slice(2,7)}`,unitId=`ingredient-unit-${idx}-${Math.random().toString(36).slice(2,7)}`;const p=productById(i.productId);const unit=i.unit||p?.baseUnit||'g';const amount=i.amount!=null?i.amount:(p?ingredientBaseAmount(i,p)/unitFactor(p,unit):i.grams||'');return `<div class="item ingredient-picker"><div class="searchable-select"><label>Wyszukaj produkt<input type="search" class="ingredient-product-search" data-target="${selectId}" autocomplete="off" placeholder="Wpisz nazwę lub kategorię…"></label><label>Produkt<select id="${selectId}" name="productId" class="ingredient-product-select" data-unit-target="${unitId}" required><option value="">Wybierz…</option>${productOptions(i.productId||'')}</select></label></div><label class="ingredient-amount">Ilość<input name="ingredientAmount" type="number" min="0.01" step="0.01" required value="${amount??''}"></label><label>Jednostka<select id="${unitId}" name="ingredientUnit" required>${p?unitOptions(p,unit):'<option value="g">g</option>'}</select></label><button type="button" class="icon-btn danger" onclick="this.parentElement.remove()" aria-label="Usuń składnik">×</button></div>`}
function mealForm(m){
  const selectedType=m?.mealType||'Śniadanie';
  const initialTime=m?.time||suggestedMealTime(selectedType);
  openModal(m?'Edytuj posiłek':'Dodaj posiłek',`<div class="form-grid"><label>Data<input name="date" type="date" required value="${m?.date||new Date().toISOString().slice(0,10)}"></label><label>Godzina<input name="time" id="mealTime" type="time" value="${initialTime}"><small id="mealTimeHint" class="field-help">Sugerowana godzina dla wybranego posiłku.</small></label><label>Typ posiłku<select name="mealType" id="mealType">${['Śniadanie','II śniadanie','Obiad','Podwieczorek','Kolacja','Przekąska','Inne'].map(x=>`<option ${selectedType===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Liczba porcji<input name="portions" type="number" min="0.25" step="0.25" required value="${m?.portions??1}"></label><label class="full">Wyszukaj przepis<input type="search" id="recipeSearch" autocomplete="off" placeholder="Wpisz nazwę przepisu…"></label><label class="full">Przepis<select name="recipeId" id="recipeSelect" required></select><small id="recipeSearchInfo" class="field-help"></small></label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const x={id:m?.id||uid(),date:fd.get('date'),time:fd.get('time'),mealType:fd.get('mealType'),recipeId:fd.get('recipeId'),portions:Math.max(0.25,num(fd.get('portions'))||1)};m?Object.assign(m,x):state.data.dietPlan.push(x);closeModal();await save()});
  const fill=()=>{const type=$('#mealType').value,q=($('#recipeSearch').value||'').trim().toLowerCase(),select=$('#recipeSelect'),current=select.value||m?.recipeId||'';const rs=state.data.recipes.filter(r=>r.mealType===type&&(!q||r.name.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name));select.innerHTML=`<option value="">Wybierz przepis…</option>${rs.map(r=>`<option value="${r.id}" ${current===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}`;$('#recipeSearchInfo').textContent=rs.length?`Dostępne przepisy: ${rs.length}`:'Brak przepisów pasujących do typu i wyszukiwania.'};
  const timeInput=$('#mealTime');
  const timeHint=$('#mealTimeHint');
  let timeChangedManually=Boolean(m?.time);
  const updateSuggestedTime=()=>{const suggestion=suggestedMealTime($('#mealType').value);if(!timeChangedManually)timeInput.value=suggestion;timeHint.textContent=`Sugerowana godzina: ${suggestion}. Możesz ją zmienić ręcznie.`};
  timeInput.oninput=()=>{timeChangedManually=true;timeHint.textContent='Godzina ustawiona ręcznie.'};
  $('#mealType').onchange=()=>{if(!m)timeChangedManually=false;updateSuggestedTime();fill()};
  $('#recipeSearch').oninput=fill;
  updateSuggestedTime();
  fill()
}
function measurementForm(m){openModal(m?'Edytuj pomiar':'Dodaj pomiar',`<div class="form-grid"><label>Data<input name="date" type="date" required value="${m?.date||new Date().toISOString().slice(0,10)}"></label><label>Masa (kg)<input name="weight" type="number" step="0.1" value="${m?.weight??''}"></label><label>Talia (cm)<input name="waist" type="number" step="0.1" value="${m?.waist??''}"></label><label>Klatka piersiowa (cm)<input name="chest" type="number" step="0.1" value="${m?.chest??''}"></label><label class="full">Notatki<textarea name="notes">${esc(m?.notes||'')}</textarea></label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const x={id:m?.id||uid(),date:fd.get('date'),weight:num(fd.get('weight'))||null,waist:num(fd.get('waist'))||null,chest:num(fd.get('chest'))||null,notes:fd.get('notes').trim()};m?Object.assign(m,x):state.data.measurements.push(x);closeModal();await save()})}
document.addEventListener('click',async e=>{const t=e.target.closest('button,[data-nav],[data-toggle-shopping]');if(!t)return;if(t.dataset.view)return go(t.dataset.view);if(t.dataset.nav)return go(t.dataset.nav);if(t.dataset.close!==undefined)return closeModal();if(t.dataset.action&&actions[t.dataset.action])return actions[t.dataset.action]();if(t.dataset.toggleShopping){const x=(state.data.shoppingList||[]).find(i=>i.id===t.dataset.toggleShopping);if(x){x.purchased=!x.purchased;await save()}return}const map=[['editProduct','products',productForm],['deleteProduct','products'],['editRecipe','recipes',recipeForm],['deleteRecipe','recipes'],['editMeal','dietPlan',mealForm],['deleteMeal','dietPlan'],['editMeasurement','measurements',measurementForm],['deleteMeasurement','measurements'],['editShopping','shoppingList',shoppingForm],['deleteShopping','shoppingList']];for(const [key,arr,fn] of map){const id=t.dataset[key];if(id){const obj=state.data[arr].find(x=>x.id===id);if(key.startsWith('edit'))return fn(obj);if(confirm('Usunąć ten element?')){state.data[arr]=state.data[arr].filter(x=>x.id!==id);if(arr==='products')state.data.recipes.forEach(r=>r.ingredients=(r.ingredients||[]).filter(i=>i.productId!==id));if(arr==='recipes')state.data.dietPlan=state.data.dietPlan.filter(x=>x.recipeId!==id);await save()}return}}});
const modalClose=$('#modalClose'),modal=$('#modal'),syncBtn=$('#syncBtn'),installBtn=$('#installBtn');if(modalClose)modalClose.onclick=closeModal;if(modal)modal.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});if(syncBtn)syncBtn.onclick=load;
document.addEventListener('input',e=>{if(e.target.matches('.ingredient-product-search')){const select=document.getElementById(e.target.dataset.target);if(!select)return;const current=select.value;select.innerHTML=`<option value="">Wybierz…</option>${productOptions(current,e.target.value)}`;if(current&&[...select.options].some(o=>o.value===current))select.value=current}});
document.addEventListener('change',e=>{if(e.target.matches('.ingredient-product-select')){const p=productById(e.target.value),unit=document.getElementById(e.target.dataset.unitTarget);if(unit)unit.innerHTML=p?unitOptions(p,p.baseUnit):'<option value="g">g</option>'}});
document.addEventListener('change',async e=>{if(e.target.id==='jsonImport'){const file=e.target.files[0];if(!file)return;try{const d=JSON.parse(await file.text());if(!Array.isArray(d.products)||!Array.isArray(d.recipes)||!Array.isArray(d.dietPlan)||!Array.isArray(d.measurements))throw Error('Nieprawidłowy format');d.shoppingList=Array.isArray(d.shoppingList)?d.shoppingList:[];const legacy=num(d.version)<3;d.products=d.products.map(p=>normalizeProductUnits({...p,category:normalizeCategory(p.category,p.name,legacy)}));d.shoppingList=d.shoppingList.map(x=>({...x,category:normalizeCategory(x.category,x.name,legacy)}));d.dietPlan=d.dietPlan.map(m=>({...m,portions:Math.max(0.25,num(m.portions)||1)}));d.version=5;if(confirm('Zastąpić wszystkie dane zawartością pliku?')){state.data=d;await save()}}catch(err){toast('Nieprawidłowy plik JSON')}finally{e.target.value=''}}if(e.target.id==='excelImport'){const file=e.target.files[0];if(!file)return;try{await importExcel(file)}catch(err){console.error(err);toast(`Błąd importu Excel: ${err.message}`)}finally{e.target.value=''}}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;if(installBtn)installBtn.classList.remove('hidden')});if(installBtn)installBtn.onclick=async()=>{if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;installBtn.classList.add('hidden')}};
render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(console.error));
load();
