const API = '/api/data';
const state = { data: { version:7, updatedAt:null, products:[], recipes:[], dietPlan:[], measurements:[], shoppingList:[], settings:{}, dayTemplates:[], backups:[] }, view:'dashboard', installPrompt:null, saving:false, productSearch:'', recipeSearch:'', recipeFilter:'all', planMode:'list', planWeekStart:null, loadedUpdatedAt:null, undoTimer:null, undoSnapshot:null };
const $ = (s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>Number(v)||0; const fmt=v=>num(v).toLocaleString('pl-PL',{maximumFractionDigits:1});
function toast(msg,actionLabel='',action=null,duration=3000){const t=$('#toast');clearTimeout(t._timer);t.innerHTML=`<span>${esc(msg)}</span>${actionLabel?`<button type="button" id="toastAction">${esc(actionLabel)}</button>`:''}`;t.classList.remove('hidden');if(actionLabel&&action){$('#toastAction')?.addEventListener('click',async()=>{t.classList.add('hidden');await action()},{once:true})}t._timer=setTimeout(()=>t.classList.add('hidden'),duration)}
function setStatus(text,bad=false){const e=$('#syncStatus');e.textContent=text;e.style.color=bad?'#a62929':''}
const COMMON_UNITS=['sztuka','kromka','szklanka','łyżka','łyżeczka','garść','plaster','opakowanie'];
const SHOP_CATEGORIES=['Warzywa i owoce','Mięso i ryby','Nabiał i jaja','Pieczywo i wypieki','Produkty zbożowe','Przetwory i suche produkty','Tłuszcze','Przyprawy i dodatki','Inne'];
const MEAL_TIME_SUGGESTIONS={ 'Śniadanie':'08:00','II śniadanie':'11:00','Obiad':'15:00','Podwieczorek':'17:30','Kolacja':'20:00','Przekąska':'13:00','Inne':'12:00' };
function suggestedMealTime(mealType){return state.data.settings?.mealTimes?.[mealType]||MEAL_TIME_SUGGESTIONS[mealType]||'12:00'}
function inferProductCategory(name=''){const n=String(name).toLowerCase();const rules=[
  ['Warzywa i owoce',['jabł','banan','grusz','pomidor','ogór','papryk','cukini','marchew','broku','szpinak','sałat','cebula','czosnek','pietrusz','seler','rzodk','winogron','grejpfrut','ananas','cytryn','fasolka szparag','roszpon','kapust']],
  ['Mięso i ryby',['kurcz','indyk','dorsz','łoso','tuńczy','wołow','wieprz','szynk','wędlin','mięso','ryba']],
  ['Nabiał i jaja',['mleko','jogurt','kefir','ser ','serek','twar','feta','mozzarell','parmezan','gouda','ricotta','jaj']],
  ['Pieczywo i wypieki',['chleb','bułk','pieczyw','tortill','wafl']],
  ['Produkty zbożowe',['płatki','ryż','makaron','kasza','kuskus','mąka','otręb','polenta']],
  ['Przetwory i suche produkty',['fasola','ciecierzyc','kukurydz','hummus','oliwk','pomidor suszon','żurawin','rodzyn','śliwk suszon','dżem','orzech','migdał','słonecznik','pestk','sezam','siemię']],
  ['Tłuszcze',['oliwa','olej','masło','awokado']],
  ['Przyprawy i dodatki',['sól','pieprz','cynamon','zioła','oregano','bazyl','curry','musztard','ocet','kakao','miód','czekolad','wiórki kokos','koperek','szczypior']]
];for(const [cat,words] of rules)if(words.some(w=>n.includes(w)))return cat;return 'Inne'}
function normalizeCategory(category,name='',inferLegacyOther=false){const value=String(category||'').trim();if(SHOP_CATEGORIES.includes(value)&&!(inferLegacyOther&&value==='Inne'))return value;return inferProductCategory(name)}
function normalizeProductUnits(p){const baseUnit=p.baseUnit==='ml'?'ml':'g';const conversions=(p.conversions&&typeof p.conversions==='object')?p.conversions:{};return {...p,baseUnit,conversions}}
function unitFactor(p,unit){if(!p)return 1;if(unit===p.baseUnit)return 1;if(unit==='kg'&&p.baseUnit==='g')return 1000;if(unit==='l'&&p.baseUnit==='ml')return 1000;return num(p.conversions?.[unit])||1}
function ingredientBaseAmount(i,p){if(i.baseAmount!=null)return num(i.baseAmount);if(i.grams!=null)return num(i.grams);return num(i.amount)*unitFactor(p,i.unit||p?.baseUnit||'g')}
function ingredientDisplay(i,p){const unit=i.unit||p?.baseUnit||'g';const amount=i.amount!=null?num(i.amount):(ingredientBaseAmount(i,p)/unitFactor(p,unit));return `${fmt(amount)} ${unit}`}
function availableUnits(p){if(!p)return ['g'];const units=[p.baseUnit];if(p.baseUnit==='g')units.push('kg');if(p.baseUnit==='ml')units.push('l');for(const u of COMMON_UNITS)if(num(p.conversions?.[u])>0)units.push(u);return [...new Set(units)]}
async function load(){setStatus('Pobieranie danych online…');try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);const r=await fetch(API,{cache:'no-store',signal:controller.signal});clearTimeout(timeout);const payload=await r.json().catch(()=>({}));if(!r.ok)throw Error(payload.error||`Błąd HTTP ${r.status}`);state.data=payload;state.data.shoppingList=Array.isArray(state.data.shoppingList)?state.data.shoppingList:[];state.data.dayTemplates=Array.isArray(state.data.dayTemplates)?state.data.dayTemplates:[];state.data.backups=Array.isArray(state.data.backups)?state.data.backups:[];state.data.settings={targets:{kcal:2100,protein:140,fat:70,carbs:230},mealTimes:{...MEAL_TIME_SUGGESTIONS},theme:'system',...(state.data.settings||{}),targets:{kcal:2100,protein:140,fat:70,carbs:230,...(state.data.settings?.targets||{})},mealTimes:{...MEAL_TIME_SUGGESTIONS,...(state.data.settings?.mealTimes||{})}};const legacyVersion=num(state.data.version)<3;state.data.products=(state.data.products||[]).map(p=>normalizeProductUnits({...p,category:normalizeCategory(p.category,p.name,legacyVersion),pantry:Boolean(p.pantry),packageSize:num(p.packageSize)||0,packagePrice:num(p.packagePrice)||0}));state.data.recipes=(state.data.recipes||[]).map(r=>({...r,favorite:Boolean(r.favorite),tags:Array.isArray(r.tags)?r.tags:[],prepTime:num(r.prepTime)||0,difficulty:r.difficulty||'Łatwy',notes:r.notes||''}));state.data.shoppingList=state.data.shoppingList.map(x=>({...x,category:normalizeCategory(x.category,x.name,legacyVersion)}));state.data.dietPlan=(state.data.dietPlan||[]).map(m=>({...m,portions:Math.max(0.25,num(m.portions)||1)}));state.data.version=7;state.loadedUpdatedAt=state.data.updatedAt||null;applyTheme();setStatus(state.data.updatedAt?`Zapisano: ${new Date(state.data.updatedAt).toLocaleString('pl-PL')}`:'Pusty plik danych – gotowe');render()}catch(e){setStatus(`Brak połączenia: ${e.message}`,true);toast('Nie udało się pobrać danych')}}
async function save(){if(state.saving)return;state.saving=true;setStatus('Zapisywanie do JSON…');try{const snapshot={at:new Date().toISOString(),data:{products:state.data.products,recipes:state.data.recipes,dietPlan:state.data.dietPlan,measurements:state.data.measurements,shoppingList:state.data.shoppingList,settings:state.data.settings,dayTemplates:state.data.dayTemplates}};state.data.backups=[snapshot,...(state.data.backups||[])].slice(0,5);const payload={...state.data,expectedUpdatedAt:state.loadedUpdatedAt};const r=await fetch(API,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(r.status===409)throw Error('Dane zmieniono na innym urządzeniu. Kliknij Odśwież i powtórz zmianę.');if(!r.ok)throw Error(body.error);state.data=body;state.loadedUpdatedAt=body.updatedAt||null;applyTheme();setStatus(`Zapisano: ${new Date(body.updatedAt).toLocaleString('pl-PL')}`);toast('Dane zapisane online')}catch(e){setStatus(`Błąd zapisu: ${e.message}`,true);toast(e.message)}finally{state.saving=false;render()}}
function go(view){state.view=view;$$('.view').forEach(e=>e.classList.toggle('active',e.id===view));$$('.tabs button,.mobile-nav button[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===view));closeMore();renderView(view)}
function render(){renderView(state.view)}
function renderView(v){({dashboard:renderDashboard,products:renderProducts,recipes:renderRecipes,plan:renderPlan,shopping:renderShopping,measurements:renderMeasurements,settings:renderSettings}[v]||renderDashboard)()}
function head(title,action,label='Dodaj'){return `<div class="section-head"><h2>${title}</h2>${action?`<button class="primary" data-action="${action}">+ ${label}</button>`:''}</div>`}
function empty(t,action='',label='Dodaj'){return `<div class="empty-state"><div class="empty-icon">○</div><h3>${t}</h3>${action?`<button class="primary" data-action="${action}">${label}</button>`:''}</div>`}
function closeMore(){const s=$('#moreSheet');if(s){s.classList.add('hidden');s.setAttribute('aria-hidden','true')}}
function openMore(){const s=$('#moreSheet');if(s){s.classList.remove('hidden');s.setAttribute('aria-hidden','false')}}
function actionMenu(items){return `<details class="action-menu"><summary aria-label="Więcej działań">⋮</summary><div class="action-menu-pop">${items.join('')}</div></details>`}
function confirmDialog({title='Potwierdź',message='',confirmLabel='Potwierdź',danger=false}={}){return new Promise(resolve=>{openModal(title,`<div class="confirm-copy"><p>${esc(message).replace(/\n/g,'<br>')}</p></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button type="submit" class="${danger?'danger-btn':'primary'}">${esc(confirmLabel)}</button></div>`,()=>{closeModal();resolve(true)});const close=$('#modalClose');const cancel=$('#modalForm [data-close]');const oldClose=close?.onclick;const cancelHandler=()=>{closeModal();resolve(false)};if(close)close.onclick=cancelHandler;if(cancel)cancel.onclick=cancelHandler;$('#modal')._confirmCleanup=()=>{if(close)close.onclick=oldClose}})}
function productById(id){return state.data.products.find(x=>x.id===id)} function recipeById(id){return state.data.recipes.find(x=>x.id===id)}
function recipeNutrition(r){return (r.ingredients||[]).reduce((a,i)=>{const p=productById(i.productId);const q=ingredientBaseAmount(i,p)/100;if(p){a.kcal+=num(p.kcal)*q;a.protein+=num(p.protein)*q;a.fat+=num(p.fat)*q;a.carbs+=num(p.carbs)*q}return a},{kcal:0,protein:0,fat:0,carbs:0})}
function mealsNutrition(meals=[]){return meals.reduce((a,m)=>{const r=recipeById(m.recipeId);if(r){const n=recipeNutrition(r),portions=Math.max(0.25,num(m.portions)||1);a.kcal+=n.kcal*portions;a.protein+=n.protein*portions;a.fat+=n.fat*portions;a.carbs+=n.carbs*portions}return a},{kcal:0,protein:0,fat:0,carbs:0})}
function daySummaryHtml(meals=[]){const n=mealsNutrition(meals),t=state.data.settings?.targets||{};const bar=(label,val,target,unit)=>`<div class="goal-row"><div><span>${label}</span><strong>${fmt(val)} / ${fmt(target)} ${unit}</strong></div><progress max="${target||1}" value="${Math.min(val,target||1)}"></progress></div>`;return `<div class="day-summary"><div><strong>${fmt(n.kcal)}</strong><span>kcal</span></div><div><strong>${fmt(n.protein)} g</strong><span>białko</span></div><div><strong>${fmt(n.fat)} g</strong><span>tłuszcz</span></div><div><strong>${fmt(n.carbs)} g</strong><span>węglowodany</span></div></div><div class="goal-bars">${bar('Kalorie',n.kcal,num(t.kcal),'kcal')}${bar('Białko',n.protein,num(t.protein),'g')}${bar('Tłuszcz',n.fat,num(t.fat),'g')}${bar('Węglowodany',n.carbs,num(t.carbs),'g')}</div>`}
function applyTheme(){const theme=state.data.settings?.theme||'system';document.documentElement.dataset.theme=theme}
function planWarnings(meals){const w=[];const sorted=[...meals].sort((a,b)=>(a.time||'').localeCompare(b.time||''));for(let i=1;i<sorted.length;i++){const [h1,m1]=(sorted[i-1].time||'00:00').split(':').map(Number),[h2,m2]=(sorted[i].time||'00:00').split(':').map(Number);if((h2*60+m2)-(h1*60+m1)>360)w.push(`Długa przerwa między ${sorted[i-1].time} a ${sorted[i].time}.`)}if(!meals.some(m=>m.mealType==='Obiad'))w.push('Brak obiadu.');const n=mealsNutrition(meals),t=state.data.settings?.targets||{};if(t.kcal&&Math.abs(n.kcal-t.kcal)/t.kcal>.15)w.push(n.kcal<t.kcal?'Kaloryczność jest ponad 15% poniżej celu.':'Kaloryczność jest ponad 15% powyżej celu.');return w.length?`<div class="warnings">${w.map(x=>`<div>⚠ ${esc(x)}</div>`).join('')}</div>`:''}
function measurementChartHtml(){const pts=[...state.data.measurements].filter(x=>x.weight).sort((a,b)=>a.date.localeCompare(b.date)).slice(-20);if(pts.length<2)return '<p>Dodaj co najmniej dwa pomiary masy ciała.</p>';const vals=pts.map(x=>num(x.weight)),min=Math.min(...vals)-1,max=Math.max(...vals)+1,w=600,h=180;const xy=pts.map((p,i)=>({x:20+i*(w-40)/(pts.length-1),y:20+(max-num(p.weight))*(h-40)/(max-min)}));return `<svg class="weight-chart" viewBox="0 0 ${w} ${h}" role="img"><polyline points="${xy.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="currentColor" stroke-width="3"/>${xy.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="4"><title>${pts[i].date}: ${pts[i].weight} kg</title></circle>`).join('')}</svg><p>Zmiana: ${fmt(vals.at(-1)-vals[0])} kg · ${pts[0].date}–${pts.at(-1).date}</p>`}
function weekStart(date=new Date()){const d=new Date(typeof date==='string'?date+'T12:00:00':date);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function weeklyPlanHtml(list){
  const start=state.planWeekStart||weekStart();
  const days=Array.from({length:7},(_,i)=>shiftIsoDate(start,i));
  const types=['Śniadanie','II śniadanie','Obiad','Podwieczorek','Kolacja','Przekąska','Inne'];
  const rangeLabel=`${new Date(start+'T12:00').toLocaleDateString('pl-PL',{day:'2-digit',month:'2-digit'})}–${new Date(days[6]+'T12:00').toLocaleDateString('pl-PL',{day:'2-digit',month:'2-digit',year:'numeric'})}`;
  return `<div class="week-nav panel"><button class="secondary" data-action="previous-week">← Poprzedni</button><strong>${rangeLabel}</strong><button class="secondary" data-action="current-week">Bieżący tydzień</button><button class="secondary" data-action="next-week">Następny →</button></div>${mobileWeekHtml(list,days)}<div class="weekly-wrap desktop-week"><table class="weekly-table"><thead><tr><th>Posiłek</th>${days.map(d=>{const dayMeals=list.filter(m=>m.date===d),n=mealsNutrition(dayMeals);return `<th><div class="week-day-head"><span>${new Date(d+'T12:00').toLocaleDateString('pl-PL',{weekday:'short',day:'2-digit',month:'2-digit'})}</span><button type="button" class="week-delete-day" data-delete-day="${d}" title="Usuń cały dzień" aria-label="Usuń wszystkie posiłki z dnia ${d}">🗑</button></div><small>${fmt(n.kcal)} kcal · ${dayMeals.length} pos.</small></th>`}).join('')}</tr></thead><tbody>${types.map(t=>`<tr><th>${t}</th>${days.map(d=>{const ms=list.filter(m=>m.date===d&&m.mealType===t);return `<td>${ms.map(m=>`<div class="week-meal-entry"><button type="button" class="week-meal" data-edit-meal="${m.id}"><strong>${esc(recipeById(m.recipeId)?.name||'—')}</strong><small>${esc(m.time||'')} · ${fmt(m.portions||1)} por.</small></button><button type="button" class="week-delete-meal" data-delete-meal="${m.id}" title="Usuń posiłek" aria-label="Usuń posiłek">×</button></div>`).join('')}<button class="week-add" data-add-meal-date="${d}" data-add-meal-type="${esc(t)}">＋</button></td>`}).join('')}</tr>`).join('')}</tbody><tfoot><tr><th>Suma dnia</th>${days.map(d=>{const n=mealsNutrition(list.filter(m=>m.date===d));return `<td><b>${fmt(n.kcal)} kcal</b><small>B ${fmt(n.protein)} · T ${fmt(n.fat)} · W ${fmt(n.carbs)}</small></td>`}).join('')}</tr></tfoot></table></div>`
}

function mobileWeekHtml(list,days){return `<div class="mobile-week">${days.map(d=>{const items=list.filter(m=>m.date===d).sort((a,b)=>(a.time||'').localeCompare(b.time||'')),n=mealsNutrition(items);return `<article class="mobile-day-card"><header><div><h3>${new Date(d+'T12:00').toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long'})}</h3><p>${fmt(n.kcal)} kcal · B ${fmt(n.protein)} · T ${fmt(n.fat)} · W ${fmt(n.carbs)}</p></div>${actionMenu([`<button data-action="copy-day-many" data-source-date="${d}">Kopiuj dzień</button>`,`<button class="danger-text" data-delete-day="${d}">Wyczyść dzień</button>`])}</header><div class="mobile-day-meals">${items.length?items.map(m=>`<div class="mobile-meal-row"><button data-edit-meal="${m.id}"><time>${esc(m.time||'--:--')}</time><span><b>${esc(m.mealType||'Posiłek')}</b><small>${esc(recipeById(m.recipeId)?.name||'—')}</small></span></button>${actionMenu([`<button data-edit-meal="${m.id}">Edytuj</button>`,`<button class="danger-text" data-delete-meal="${m.id}">Usuń</button>`])}</div>`).join(''):empty('Brak posiłków')}</div><button class="week-add-mobile" data-add-meal-date="${d}" data-add-meal-type="Śniadanie">+ Dodaj posiłek</button></article>`}).join('')}</div>`}
function copyPreviousWeek(){const defaultTarget=state.planWeekStart||weekStart();openModal('Kopiuj poprzedni tydzień',`<div class="form-grid"><label class="full">Poniedziałek tygodnia docelowego<input name="target" type="date" required value="${defaultTarget}"></label><label class="full"><input name="replace" type="checkbox" checked> Zastąp istniejące posiłki w tygodniu docelowym</label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Kopiuj tydzień</button></div>`,async fd=>{const target=weekStart(fd.get('target')),source=shiftIsoDate(target,-7),sourceEnd=shiftIsoDate(source,6),src=state.data.dietPlan.filter(m=>m.date>=source&&m.date<=sourceEnd);if(!src.length)return toast('Poprzedni tydzień jest pusty');if(fd.get('replace')==='on')state.data.dietPlan=state.data.dietPlan.filter(m=>m.date<target||m.date>shiftIsoDate(target,6));state.data.dietPlan.push(...src.map(m=>({...m,id:uid(),date:shiftIsoDate(m.date,7)})));state.planWeekStart=target;closeModal();await save();toast(`Skopiowano ${src.length} posiłków`)})}
function copyDayToDatesForm(){const today=state.copySourceDate||new Date().toISOString().slice(0,10);state.copySourceDate=null;openModal('Kopiuj dzień na wybrane daty',`<div class="form-grid"><label>Data źródłowa<input name="source" type="date" required value="${today}"></label><label class="full">Daty docelowe<input name="targets" required placeholder="np. 2026-06-22, 2026-06-24, 2026-06-26"><small class="field-help">Wpisz daty oddzielone przecinkami.</small></label><label class="full"><input name="replace" type="checkbox" checked> Zastąp istniejące posiłki w datach docelowych</label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Kopiuj</button></div>`,async fd=>{const source=fd.get('source'),targets=String(fd.get('targets')||'').split(',').map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&x!==source),src=state.data.dietPlan.filter(m=>m.date===source);if(!src.length)return toast('Dzień źródłowy jest pusty');if(!targets.length)return toast('Podaj co najmniej jedną poprawną datę');if(fd.get('replace')==='on')state.data.dietPlan=state.data.dietPlan.filter(m=>!targets.includes(m.date));for(const date of targets)state.data.dietPlan.push(...src.map(m=>({...m,id:uid(),date})));closeModal();await save();toast(`Skopiowano dzień na ${targets.length} dat`)})}
function templatesForm(){const templates=state.data.dayTemplates||[],today=new Date().toISOString().slice(0,10);openModal('Szablony dni',`<div class="form-grid"><label>Data<input name="date" type="date" required value="${today}"></label><label>Operacja<select name="mode" id="templateMode"><option value="save">Zapisz dzień jako nowy szablon</option><option value="apply">Zastosuj istniejący szablon</option></select></label><label class="full" id="templateNameWrap">Nazwa szablonu<input name="name" value="Dzień pracy"></label><label class="full hidden" id="templateSelectWrap">Szablon<select name="templateId">${templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const date=fd.get('date'),mode=fd.get('mode');if(mode==='save'){const meals=state.data.dietPlan.filter(m=>m.date===date).map(({id,date,...x})=>x),name=String(fd.get('name')||'').trim();if(!meals.length)return toast('Wybrany dzień jest pusty');if(!name)return toast('Podaj nazwę szablonu');state.data.dayTemplates.push({id:uid(),name,meals})}else{const t=templates.find(x=>x.id===fd.get('templateId'));if(!t)return toast('Wybierz szablon');const existing=state.data.dietPlan.filter(m=>m.date===date);if(existing.length&&!await confirmDialog({title:'Zastąpić plan dnia?',message:`Dzień zawiera ${existing.length} posiłków.`,confirmLabel:'Zastąp'}))return;state.data.dietPlan=state.data.dietPlan.filter(m=>m.date!==date);state.data.dietPlan.push(...t.meals.map(m=>({...m,id:uid(),date})))}closeModal();await save();toast(mode==='save'?'Szablon zapisany':'Szablon zastosowany')});const mode=$('#templateMode'),toggle=()=>{$('#templateNameWrap').classList.toggle('hidden',mode.value!=='save');$('#templateSelectWrap').classList.toggle('hidden',mode.value!=='apply')};mode.onchange=toggle;toggle()}
function renderDashboard(){
  const d=state.data;const today=new Date().toISOString().slice(0,10);const meals=d.dietPlan.filter(x=>x.date===today).sort((a,b)=>(a.time||'').localeCompare(b.time||''));
  const n=mealsNutrition(meals),targets=d.settings?.targets||{};const now=new Date().toTimeString().slice(0,5);const next=meals.find(m=>(m.time||'')>=now)||meals[0];const nextRecipe=next?recipeById(next.recipeId):null;
  $('#dashboard').innerHTML=`<div class="welcome-head"><div><span class="eyebrow">Dzisiaj</span><h2>${new Date(today+'T12:00').toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long'})}</h2></div><button class="primary" data-action="add-meal">+ Dodaj posiłek</button></div>
  <div class="today-hero panel"><div class="calorie-ring"><strong>${fmt(n.kcal)}</strong><span>z ${fmt(targets.kcal||2100)} kcal</span></div><div class="today-main"><h3>${meals.length?`${meals.length} zaplanowane posiłki`:'Brak planu na dziś'}</h3><p>${next&&nextRecipe?`Następny: <b>${esc(next.mealType)}</b> o ${esc(next.time||'--:--')}<br>${esc(nextRecipe.name)}`:'Dodaj pierwszy posiłek lub skopiuj wczorajszy dzień.'}</p>${goalBarsCompact(n,targets)}</div></div>
  <div class="quick-actions compact-actions"><button class="secondary" data-action="copy-previous-day">↺ Skopiuj wczoraj</button><button class="secondary" data-action="add-measurement">＋ Pomiar</button><button class="secondary" data-action="generate-shopping">▣ Wygeneruj zakupy</button></div>
  <div class="dashboard-grid"><section class="panel"><div class="panel-title"><h3>Dzisiejszy plan</h3><button class="text-btn" data-nav="plan">Zobacz plan →</button></div>${meals.length?meals.map(mealHtml).join(''):empty('Nie masz jeszcze posiłków na dziś','add-meal','Dodaj posiłek')}</section><section class="panel"><div class="panel-title"><h3>Postępy</h3><button class="text-btn" data-nav="measurements">Pomiary →</button></div>${measurementChartHtml()}</section></div>`
}
function goalBarsCompact(n,t){const row=(l,v,max,u)=>`<div><span>${l}</span><progress max="${max||1}" value="${Math.min(v,max||1)}"></progress><b>${fmt(v)} / ${fmt(max)} ${u}</b></div>`;return `<div class="compact-goals">${row('Białko',n.protein,num(t.protein),'g')}${row('Tłuszcz',n.fat,num(t.fat),'g')}${row('Węglowodany',n.carbs,num(t.carbs),'g')}</div>`}

function rowsFromSheet(wb,name){const X=ensureXlsx();const ws=wb.Sheets[name];return ws?X.utils.sheet_to_json(ws,{defval:'',raw:false}):[]}
function cell(row,...names){for(const n of names){if(row[n]!==undefined&&row[n]!==null&&String(row[n]).trim()!=='')return row[n]}return ''}
function excelNumber(v){if(v===''||v===null||v===undefined)return 0;return Number(String(v).replace(',','.'))||0}
function excelDate(v){if(!v)return '';const text=String(v).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;const m=text.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(text);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
async function importExcel(file){
  const X=ensureXlsx();const wb=X.read(await file.arrayBuffer(),{type:'array',cellDates:true});
  const productRows=rowsFromSheet(wb,'Produkty'),recipeRows=rowsFromSheet(wb,'Przepisy'),ingredientRows=rowsFromSheet(wb,'Skladniki'),planRows=rowsFromSheet(wb,'Plan_diety'),shoppingRows=rowsFromSheet(wb,'Lista_zakupow'),measurementRows=rowsFromSheet(wb,'Pomiary');
  if(!productRows.length&&!recipeRows.length&&!planRows.length&&!measurementRows.length)throw Error('Brak obsługiwanych arkuszy');
  const products=productRows.filter(r=>String(cell(r,'Nazwa','Produkt')).trim()).map(r=>({id:String(cell(r,'ID')||uid()),name:String(cell(r,'Nazwa','Produkt')).trim(),kcal:excelNumber(cell(r,'Kalorie_100g','Kalorie','kcal')),protein:excelNumber(cell(r,'Bialko_100g','Bialko')),fat:excelNumber(cell(r,'Tluszcz_100g','Tluszcz')),carbs:excelNumber(cell(r,'Weglowodany_100g','Weglowodany')),category:normalizeCategory(String(cell(r,'Kategoria')||'').trim(),String(cell(r,'Nazwa','Produkt')).trim(),true),baseUnit:String(cell(r,'Jednostka_bazowa')||'g')==='ml'?'ml':'g',conversions:(()=>{try{return JSON.parse(String(cell(r,'Przeliczniki_JSON')||'{}'))}catch{return {}}})()}));
  const productByExcelId=new Map(products.map(p=>[p.id,p]));const productByName=new Map(products.map(p=>[p.name.toLowerCase(),p]));
  const recipes=recipeRows.filter(r=>String(cell(r,'Nazwa','Przepis')).trim()).map(r=>({id:String(cell(r,'ID')||uid()),name:String(cell(r,'Nazwa','Przepis')).trim(),mealType:String(cell(r,'Typ_posilku','Typ posilku')||'Inne').trim(),instructions:String(cell(r,'Przygotowanie','Sposob przygotowania')||'').trim(),ingredients:[]}));
  const recipeByExcelId=new Map(recipes.map(r=>[r.id,r]));const recipeByName=new Map(recipes.map(r=>[r.name.toLowerCase(),r]));
  for(const row of ingredientRows){const recipe=recipeByExcelId.get(String(cell(row,'ID_przepisu')))||recipeByName.get(String(cell(row,'Nazwa_przepisu')).trim().toLowerCase());const product=productByExcelId.get(String(cell(row,'ID_produktu')))||productByName.get(String(cell(row,'Nazwa_produktu')).trim().toLowerCase());const amount=excelNumber(cell(row,'Ilosc','Ilosc_g'));const unit=String(cell(row,'Jednostka')||product?.baseUnit||'g');const baseAmount=excelNumber(cell(row,'Ilosc_bazowa'))||amount*unitFactor(product,unit);if(recipe&&product&&amount>0)recipe.ingredients.push({productId:product.id,amount,unit,baseAmount,grams:baseAmount})}
  const dietPlan=planRows.filter(r=>excelDate(cell(r,'Data'))).map(r=>{const recipe=recipeByExcelId.get(String(cell(r,'ID_przepisu')))||recipeByName.get(String(cell(r,'Nazwa_przepisu')).trim().toLowerCase());return {id:String(cell(r,'ID')||uid()),date:excelDate(cell(r,'Data')),time:String(cell(r,'Godzina')||''),mealType:String(cell(r,'Typ_posilku','Typ posilku')||recipe?.mealType||'Inne'),recipeId:recipe?.id||'',portions:Math.max(0.25,excelNumber(cell(r,'Liczba_porcji','Porcje'))||1)}}).filter(x=>x.recipeId);
  const shoppingList=shoppingRows.filter(r=>String(cell(r,'Nazwa')).trim()).map(r=>({id:String(cell(r,'ID')||uid()),productId:'',name:String(cell(r,'Nazwa')).trim(),amount:excelNumber(cell(r,'Ilosc')),unit:String(cell(r,'Jednostka')||'g'),category:normalizeCategory(String(cell(r,'Kategoria')||'').trim(),String(cell(r,'Nazwa')).trim(),true),purchased:String(cell(r,'Kupione')).toUpperCase()==='TAK',source:String(cell(r,'Zrodlo')||'manual')}));
  const measurements=measurementRows.filter(r=>excelDate(cell(r,'Data'))).map(r=>({id:String(cell(r,'ID')||uid()),date:excelDate(cell(r,'Data')),weight:excelNumber(cell(r,'Masa_kg','Masa'))||null,waist:excelNumber(cell(r,'Talia_cm','Talia'))||null,chest:excelNumber(cell(r,'Klatka_cm','Klatka'))||null,notes:String(cell(r,'Notatki')||'').trim()}));
  if(!await confirmDialog({title:'Zaimportować dane z Excela?',message:`Produkty: ${products.length}
Przepisy: ${recipes.length}
Plan: ${dietPlan.length}
Koszyk: ${shoppingList.length}
Pomiary: ${measurements.length}

Aktualne dane zostaną zastąpione.`,confirmLabel:'Importuj'}))return;
  state.data={version:7,updatedAt:null,products,recipes,dietPlan,measurements,shoppingList,settings:state.data.settings||{},dayTemplates:[],backups:[]};await save();toast('Dane z Excela zostały zaimportowane');
}

const actions={
'open-more':()=>openMore(), 'close-more':()=>closeMore(),
'add-product':()=>productForm(), 'add-recipe':()=>recipeForm(), 'add-meal':()=>mealForm(), 'add-shopping':()=>shoppingForm(), 'add-measurement':()=>measurementForm(),
'export-pdf':()=>pdfExportForm(),
'copy-previous-day':()=>copyPreviousDayForm(),
'copy-previous-week':()=>copyPreviousWeek(),
'copy-day-many':()=>copyDayToDatesForm(),
'previous-week':()=>{state.planWeekStart=shiftIsoDate(state.planWeekStart||weekStart(),-7);renderPlan()},
'next-week':()=>{state.planWeekStart=shiftIsoDate(state.planWeekStart||weekStart(),7);renderPlan()},
'current-week':()=>{state.planWeekStart=weekStart();renderPlan()},
'toggle-plan-view':()=>{state.planMode=state.planMode==='week'?'list':'week';renderPlan()},
'templates':()=>templatesForm(),
'save-settings':async()=>{state.data.settings.targets={kcal:num($('#goalKcal')?.value),protein:num($('#goalProtein')?.value),fat:num($('#goalFat')?.value),carbs:num($('#goalCarbs')?.value)};state.data.settings.mealTimes={...MEAL_TIME_SUGGESTIONS};$$('[data-meal-time]').forEach(x=>state.data.settings.mealTimes[x.dataset.mealTime]=x.value);state.data.settings.theme=$('#themeSelect')?.value||'system';await save()},
'restore-backup':async()=>{const b=state.data.backups?.[num($('#backupSelect')?.value)];if(b&&await confirmDialog({title:'Przywrócić kopię?',message:'Aktualne dane zostaną zastąpione wybraną wersją.',confirmLabel:'Przywróć'})){Object.assign(state.data,b.data);await save()}},
'generate-shopping':()=>generateShopping(), 'clear-shopping':async()=>{const count=(state.data.shoppingList||[]).length;if(!count)return toast('Koszyk jest już pusty');if(await confirmDialog({title:'Usunąć cały koszyk?',message:`Zostanie usuniętych pozycji: ${count}`,confirmLabel:'Usuń koszyk',danger:true})){state.data.shoppingList=[];await save();toast('Cały koszyk został usunięty')}}, 'clear-purchased':async()=>{state.data.shoppingList=(state.data.shoppingList||[]).filter(x=>!x.purchased);await save()},
'export-excel':()=>exportExcel(),
'export-json':()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}));a.download=`moja-dieta-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)},
'seed':async()=>{if(state.data.products.length&&!await confirmDialog({title:'Dodać dane demonstracyjne?',message:'Dane zostaną dodane do istniejących produktów i przepisów.',confirmLabel:'Dodaj'}))return;const p1={id:uid(),name:'Płatki owsiane',category:'Produkty zbożowe',kcal:370,protein:13,fat:7,carbs:60,baseUnit:'g',conversions:{'szklanka':90,'łyżka':10}},p2={id:uid(),name:'Banan',category:'Warzywa i owoce',kcal:89,protein:1.1,fat:.3,carbs:23,baseUnit:'g',conversions:{'sztuka':120}},p3={id:uid(),name:'Migdały',category:'Przetwory i suche produkty',kcal:579,protein:21,fat:50,carbs:22,baseUnit:'g',conversions:{'łyżka':15,'garść':25}};state.data.products.push(p1,p2,p3);state.data.recipes.push({id:uid(),name:'Owsianka z bananem i migdałami',mealType:'Śniadanie',instructions:'Płatki zalej gorącą wodą. Dodaj banana i posiekane migdały.',ingredients:[{productId:p1.id,amount:60,unit:'g',baseAmount:60,grams:60},{productId:p2.id,amount:1,unit:'sztuka',baseAmount:120,grams:120},{productId:p3.id,amount:20,unit:'g',baseAmount:20,grams:20}]});await save()},
'clear-all':async()=>{if(await confirmDialog({title:'Usunąć wszystkie dane?',message:'Produkty, przepisy, plan, koszyk i pomiary zostaną trwale usunięte.',confirmLabel:'Usuń wszystko',danger:true})){state.data={version:7,updatedAt:null,products:[],recipes:[],dietPlan:[],measurements:[],shoppingList:[],settings:{targets:{kcal:2100,protein:140,fat:70,carbs:230},mealTimes:{...MEAL_TIME_SUGGESTIONS},theme:'system'},dayTemplates:[],backups:[]};await save()}}
};
function conversionFields(p={}){return COMMON_UNITS.map(u=>`<label>${u} = ile ${p.baseUnit||'g'}?<input name="conv_${u}" type="number" min="0" step="0.1" value="${p.conversions?.[u]??''}" placeholder="opcjonalnie"></label>`).join('')}
function fieldsProduct(p={}){p=normalizeProductUnits(p);return `<div class="form-grid"><label class="full">Nazwa<input name="name" required value="${esc(p.name||'')}"></label><label>Kategoria<select name="category">${SHOP_CATEGORIES.map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Jednostka bazowa<select name="baseUnit"><option value="g" ${p.baseUnit==='g'?'selected':''}>g</option><option value="ml" ${p.baseUnit==='ml'?'selected':''}>ml</option></select></label><label><input name="pantry" type="checkbox" ${p.pantry?'checked':''}> Mam w domu</label><label>Wielkość opakowania<input name="packageSize" type="number" step="0.1" value="${p.packageSize||''}"></label><label>Cena opakowania (zł)<input name="packagePrice" type="number" step="0.01" value="${p.packagePrice||''}"></label><label>Kalorie / 100<input name="kcal" type="number" step="0.1" value="${p.kcal??''}"></label><label>Białko / 100<input name="protein" type="number" step="0.1" value="${p.protein??''}"></label><label>Tłuszcz / 100<input name="fat" type="number" step="0.1" value="${p.fat??''}"></label><label>Węglowodany / 100<input name="carbs" type="number" step="0.1" value="${p.carbs??''}"></label><div class="full"><h4>Jednostki domowe</h4><div class="form-grid">${conversionFields(p)}</div></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`}
function productForm(p){openModal(p?'Edytuj produkt':'Dodaj produkt',fieldsProduct(p),async fd=>{const conversions={};for(const u of COMMON_UNITS){const v=num(fd.get(`conv_${u}`));if(v>0)conversions[u]=v}const x={id:p?.id||uid(),name:fd.get('name').trim(),kcal:num(fd.get('kcal')),protein:num(fd.get('protein')),fat:num(fd.get('fat')),carbs:num(fd.get('carbs')),category:normalizeCategory(fd.get('category'),fd.get('name')),baseUnit:fd.get('baseUnit')==='ml'?'ml':'g',conversions,pantry:fd.get('pantry')==='on',packageSize:num(fd.get('packageSize')),packagePrice:num(fd.get('packagePrice'))};p?Object.assign(p,x):state.data.products.push(x);closeModal();await save()})}
function recipeForm(r){const ingredients=r?.ingredients?.length?r.ingredients:[{productId:'',amount:'',unit:'g'}];const rows=ingredients.map((i,idx)=>ingredientRow(i,idx)).join('');openModal(r?'Edytuj przepis':'Dodaj przepis',`<div class="form-grid"><label class="full">Nazwa<input name="name" required value="${esc(r?.name||'')}"></label><label>Typ posiłku<select name="mealType">${['Śniadanie','II śniadanie','Obiad','Podwieczorek','Kolacja','Przekąska','Inne'].map(x=>`<option ${r?.mealType===x?'selected':''}>${x}</option>`).join('')}</select></label><label><input name="favorite" type="checkbox" ${r?.favorite?'checked':''}> Ulubiony</label><label>Czas (min)<input name="prepTime" type="number" value="${r?.prepTime||''}"></label><label>Trudność<select name="difficulty">${['Łatwy','Średni','Trudny'].map(x=>`<option ${r?.difficulty===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Tagi (po przecinku)<input name="tags" value="${esc((r?.tags||[]).join(', '))}"></label><label class="full">Notatki<input name="notes" value="${esc(r?.notes||'')}"></label><label class="full">Sposób przygotowania<textarea name="instructions">${esc(r?.instructions||'')}</textarea></label><div class="full"><b>Składniki</b><div id="ingredientRows" class="list">${rows}</div><button type="button" class="secondary" id="addIngredient">+ Składnik</button></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const productIds=fd.getAll('productId'),amounts=fd.getAll('ingredientAmount'),units=fd.getAll('ingredientUnit');const ingredients=productIds.map((id,i)=>{const p=productById(id),amount=num(amounts[i]),unit=units[i]||p?.baseUnit||'g',baseAmount=amount*unitFactor(p,unit);return {productId:id,amount,unit,baseAmount,grams:baseAmount}}).filter(i=>i.productId&&i.amount>0);const x={id:r?.id||uid(),name:fd.get('name').trim(),mealType:fd.get('mealType'),instructions:fd.get('instructions').trim(),ingredients,favorite:fd.get('favorite')==='on',prepTime:num(fd.get('prepTime')),difficulty:fd.get('difficulty'),tags:String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),notes:fd.get('notes').trim()};r?Object.assign(r,x):state.data.recipes.push(x);closeModal();await save()});$('#addIngredient').onclick=()=>$('#ingredientRows').insertAdjacentHTML('beforeend',ingredientRow({},Date.now()))}
function productOptions(selectedId='',query=''){const q=(query||'').trim().toLowerCase();return [...state.data.products].filter(p=>!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${p.id}" ${selectedId===p.id?'selected':''}>${esc(p.name)} — ${esc(p.category||'Inne')}</option>`).join('')}
function unitOptions(p,selected=''){return availableUnits(p).map(u=>`<option value="${esc(u)}" ${selected===u?'selected':''}>${esc(u)}</option>`).join('')}
function ingredientRow(i,idx){const selectId=`ingredient-product-${idx}-${Math.random().toString(36).slice(2,7)}`,unitId=`ingredient-unit-${idx}-${Math.random().toString(36).slice(2,7)}`;const p=productById(i.productId);const unit=i.unit||p?.baseUnit||'g';const amount=i.amount!=null?i.amount:(p?ingredientBaseAmount(i,p)/unitFactor(p,unit):i.grams||'');return `<div class="item ingredient-picker"><div class="searchable-select"><label>Wyszukaj produkt<input type="search" class="ingredient-product-search" data-target="${selectId}" autocomplete="off" placeholder="Wpisz nazwę lub kategorię…"></label><label>Produkt<select id="${selectId}" name="productId" class="ingredient-product-select" data-unit-target="${unitId}" required><option value="">Wybierz…</option>${productOptions(i.productId||'')}</select></label></div><label class="ingredient-amount">Ilość<input name="ingredientAmount" type="number" min="0.01" step="0.01" required value="${amount??''}"></label><label>Jednostka<select id="${unitId}" name="ingredientUnit" required>${p?unitOptions(p,unit):'<option value="g">g</option>'}</select></label><button type="button" class="icon-btn danger" onclick="this.parentElement.remove()" aria-label="Usuń składnik">×</button></div>`}
function mealForm(m){
  const selectedType=m?.mealType||'Śniadanie';
  const initialTime=m?.time||suggestedMealTime(selectedType);
  openModal(m&&!m._new?'Edytuj posiłek':'Dodaj posiłek',`<div class="form-grid"><label>Data<input name="date" type="date" required value="${m?.date||new Date().toISOString().slice(0,10)}"></label><label>Godzina<input name="time" id="mealTime" type="time" value="${initialTime}"><small id="mealTimeHint" class="field-help">Sugerowana godzina dla wybranego posiłku.</small></label><label>Typ posiłku<select name="mealType" id="mealType">${['Śniadanie','II śniadanie','Obiad','Podwieczorek','Kolacja','Przekąska','Inne'].map(x=>`<option ${selectedType===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Liczba porcji<input name="portions" type="number" min="0.25" step="0.25" required value="${m?.portions??1}"></label><label class="full">Wyszukaj przepis<input type="search" id="recipeSearch" autocomplete="off" placeholder="Wpisz nazwę przepisu…"></label><label class="full">Przepis<select name="recipeId" id="recipeSelect" required></select><small id="recipeSearchInfo" class="field-help"></small></label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const x={id:(m&&!m._new?m.id:null)||uid(),date:fd.get('date'),time:fd.get('time'),mealType:fd.get('mealType'),recipeId:fd.get('recipeId'),portions:Math.max(0.25,num(fd.get('portions'))||1)};m&&!m._new?Object.assign(m,x):state.data.dietPlan.push(x);closeModal();await save()});
  const fill=()=>{const type=$('#mealType').value,q=($('#recipeSearch').value||'').trim().toLowerCase(),select=$('#recipeSelect'),current=select.value||m?.recipeId||'';const rs=state.data.recipes.filter(r=>r.mealType===type&&(!q||r.name.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name));select.innerHTML=`<option value="">Wybierz przepis…</option>${rs.map(r=>`<option value="${r.id}" ${current===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}`;$('#recipeSearchInfo').textContent=rs.length?`Dostępne przepisy: ${rs.length}`:'Brak przepisów pasujących do typu i wyszukiwania.'};
  const timeInput=$('#mealTime');
  const timeHint=$('#mealTimeHint');
  let timeChangedManually=Boolean(m?.time);
  const updateSuggestedTime=()=>{const suggestion=suggestedMealTime($('#mealType').value);if(!timeChangedManually)timeInput.value=suggestion;timeHint.textContent=`Sugerowana godzina: ${suggestion}. Możesz ją zmienić ręcznie.`};
  timeInput.oninput=()=>{timeChangedManually=true;timeHint.textContent='Godzina ustawiona ręcznie.'};
  $('#mealType').onchange=()=>{if(!m||m._new)timeChangedManually=false;updateSuggestedTime();fill()};
  $('#recipeSearch').oninput=fill;
  updateSuggestedTime();
  fill()
}


function shiftIsoDate(date,days){
  const d=new Date(date+'T12:00:00');
  d.setDate(d.getDate()+days);
  return d.toISOString().slice(0,10)
}
function suggestedCopyTargetDate(){
  const dates=(state.data.dietPlan||[]).map(x=>x.date).filter(Boolean).sort();
  return dates.length?shiftIsoDate(dates[dates.length-1],1):new Date().toISOString().slice(0,10)
}
function copyPreviousDayForm(){
  const target=suggestedCopyTargetDate();
  openModal('Skopiuj poprzedni dzień',`<div class="form-grid"><label class="full">Dzień docelowy<input name="targetDate" id="copyTargetDate" type="date" required value="${target}"></label><div class="full panel copy-day-info"><p id="copyDayInfo"></p><p class="hint">Skopiowane zostaną godziny, typy posiłków, przepisy i liczba porcji. Jeżeli dzień docelowy zawiera już posiłki, możesz je zastąpić.</p></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Skopiuj</button></div>`,async fd=>{
    const targetDate=fd.get('targetDate');
    const sourceDate=shiftIsoDate(targetDate,-1);
    const sourceMeals=(state.data.dietPlan||[]).filter(x=>x.date===sourceDate);
    if(!sourceMeals.length){toast('Poprzedni dzień nie zawiera posiłków');return}
    const existing=(state.data.dietPlan||[]).filter(x=>x.date===targetDate);
    if(existing.length&&!await confirmDialog({title:'Zastąpić plan dnia?',message:`Dzień ${targetDate} zawiera już ${existing.length} pozycji.`,confirmLabel:'Zastąp'}))return;
    state.data.dietPlan=(state.data.dietPlan||[]).filter(x=>x.date!==targetDate);
    state.data.dietPlan.push(...sourceMeals.map(m=>({
      id:uid(),date:targetDate,time:m.time||'',mealType:m.mealType||'Inne',recipeId:m.recipeId,portions:Math.max(0.25,num(m.portions)||1)
    })));
    closeModal();
    await save();
    toast(`Skopiowano ${sourceMeals.length} posiłków z ${sourceDate}`)
  });
  const updateInfo=()=>{const targetDate=$('#copyTargetDate').value,sourceDate=targetDate?shiftIsoDate(targetDate,-1):'',count=(state.data.dietPlan||[]).filter(x=>x.date===sourceDate).length;$('#copyDayInfo').innerHTML=targetDate?`Źródło: <strong>${esc(sourceDate)}</strong> · ${count} ${count===1?'posiłek':'posiłków'}`:''};
  $('#copyTargetDate').oninput=updateInfo;
  updateInfo()
}

function pdfDateLabel(date){return new Date(date+'T12:00:00').toLocaleDateString('pl-PL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}
function romanMealNumber(index){return ['I','II','III','IV','V','VI','VII','VIII'][index]||String(index+1)}
function printableMealHtml(m,index){
  const r=recipeById(m.recipeId);if(!r)return '';
  const portions=Math.max(0.25,num(m.portions)||1),n=recipeNutrition(r);
  const ingredients=(r.ingredients||[]).map(i=>{const p=productById(i.productId),unit=i.unit||p?.baseUnit||'g';const amount=(i.amount!=null?num(i.amount):(ingredientBaseAmount(i,p)/unitFactor(p,unit)))*portions;const base=ingredientBaseAmount(i,p)*portions;const baseText=(unit!==p?.baseUnit&&p?.baseUnit)?` (${fmt(base)} ${esc(p.baseUnit)})`:'';return `<li>${esc(p?.name||'Nieznany produkt')} - ${fmt(amount)} ${esc(unit)}${baseText}</li>`}).join('');
  return `<article class="pdf-meal"><div class="pdf-meal-top"><div><div class="pdf-time">${esc(m.time||'--:--')} <span class="pdf-meal-type">${esc(m.mealType||`Posiłek ${romanMealNumber(index)}`)}</span></div><div class="pdf-date-small">${esc(pdfDateLabel(m.date))}</div></div><div class="pdf-nutrition"><b>WARTOŚCI<br>ODŻYWCZE:</b><span>Energia: ${fmt(n.kcal*portions)} kcal</span><span>Białko: ${fmt(n.protein*portions)} g</span><span>Tłuszcz: ${fmt(n.fat*portions)} g</span><span>Węglowodany: ${fmt(n.carbs*portions)} g</span></div></div><h2>${esc(r.name)}</h2>${portions!==1?`<div class="pdf-portions">Liczba porcji: ${fmt(portions)}</div>`:''}<h3>SKŁADNIKI:</h3><ul>${ingredients||'<li>Brak składników</li>'}</ul><h3>SPOSÓB PRZYGOTOWANIA:</h3><div class="pdf-instructions">${esc(r.instructions||'Brak opisu przygotowania.').replace(/\n/g,'<br>')}</div></article>`
}
function buildPrintablePlan(from,to){
  const meals=[...state.data.dietPlan].filter(m=>(!from||m.date>=from)&&(!to||m.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||''));
  const groups=meals.reduce((a,m)=>((a[m.date]??=[]).push(m),a),{});
  const days=Object.entries(groups).map(([date,items])=>`<section class="pdf-day"><header class="pdf-day-header"><strong>Moja Dieta - indywidualny plan żywieniowy</strong><span>${esc(pdfDateLabel(date))}</span></header><div class="pdf-meals pdf-cols-${Math.min(Math.max(items.length,1),4)}">${items.map((m,i)=>printableMealHtml(m,i)).join('')}</div><footer>Wygenerowano ${new Date().toLocaleDateString('pl-PL')}</footer></section>`).join('');
  return `<!doctype html><html lang="pl"><head><meta charset="utf-8"><title>Plan diety ${esc(from||'')} ${esc(to||'')}</title><style>
  @page{size:A4 landscape;margin:8mm}
*{box-sizing:border-box}
body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#171717;background:#eee;font-size:8pt;line-height:1.35}
.print-toolbar{position:sticky;top:0;z-index:2;padding:10px 14px;background:#1f6b49;color:white;display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:9pt}
.print-toolbar button{border:0;border-radius:8px;padding:9px 14px;font-size:9pt;font-weight:700;cursor:pointer}
.pdf-day{background:white;width:281mm;min-height:194mm;margin:10px auto;padding:3mm 2mm 7mm;position:relative;page-break-after:always}
.pdf-day:last-child{page-break-after:auto}
.pdf-day-header{display:flex;justify-content:space-between;align-items:center;border-bottom:.3mm solid #b8b8b8;padding:0 1mm 2mm;margin-bottom:3mm;color:#555;font-size:7.5pt;line-height:1.2}
.pdf-day-header strong{font-size:8.5pt;color:#222}
.pdf-meals{display:grid;gap:4mm;align-items:start}
.pdf-cols-1{grid-template-columns:1fr}.pdf-cols-2{grid-template-columns:repeat(2,1fr)}.pdf-cols-3{grid-template-columns:repeat(3,1fr)}.pdf-cols-4{grid-template-columns:repeat(4,1fr)}
.pdf-meal{min-width:0;padding:0 1mm;font-size:8pt;line-height:1.35;break-inside:avoid}
.pdf-meal-top{display:grid;grid-template-columns:minmax(0,1fr) 30mm;gap:2.5mm;align-items:start}
.pdf-time{font-size:10pt;font-weight:700;line-height:1.15}
.pdf-meal-type{font-weight:700}
.pdf-date-small{font-size:8.5pt;font-weight:700;line-height:1.2;margin-top:1mm}
.pdf-nutrition{font-size:6.75pt;line-height:1.25;color:#333}
.pdf-nutrition b{display:block;font-size:7pt;line-height:1.05;margin-bottom:.8mm;text-decoration:underline}
.pdf-nutrition span{display:block}
.pdf-meal h2{font-size:11pt;font-weight:700;line-height:1.16;margin:3mm 0 3.5mm}
.pdf-portions{font-size:7pt;line-height:1.2;margin-top:-2.5mm;margin-bottom:2.5mm;color:#666}
.pdf-meal h3{font-size:8.5pt;font-weight:700;line-height:1.15;text-decoration:underline;margin:3mm 0 1.6mm;letter-spacing:.01em}
.pdf-meal ul{list-style:none;padding:0;margin:0;font-size:7.8pt;line-height:1.32}
.pdf-meal li{margin:0 0 .9mm}
.pdf-instructions{font-size:7.8pt;line-height:1.38;white-space:normal}
.pdf-day footer{position:absolute;bottom:2mm;left:3mm;font-size:6.25pt;line-height:1;color:#777}
@media print{body{background:white}.print-toolbar{display:none}.pdf-day{margin:0;width:auto;min-height:0;padding-top:0}}
  </style></head><body><div class="print-toolbar"><span>Podgląd planu diety</span><button onclick="window.print()">Zapisz jako PDF / Drukuj</button></div>${days||'<div style="padding:30px">Brak posiłków w wybranym zakresie dat.</div>'}</body></html>`
}
function openPrintablePlan(from,to){const w=window.open('','_blank');if(!w){toast('Przeglądarka zablokowała nowe okno');return}w.document.open();w.document.write(buildPrintablePlan(from,to));w.document.close();setTimeout(()=>{try{w.focus();w.print()}catch{}},500)}
function pdfExportForm(){
  const dates=state.data.dietPlan.map(m=>m.date).filter(Boolean).sort();const today=new Date().toISOString().slice(0,10),from=dates[0]||today,to=dates[dates.length-1]||today;
  openModal('Eksport planu do PDF',`<div class="form-grid"><label>Data od<input name="from" type="date" required value="${from}"></label><label>Data do<input name="to" type="date" required value="${to}"></label><div class="full panel pdf-export-note"><b>Układ wydruku</b><p>Pozioma strona A4, jeden dzień na stronie, posiłki w kolumnach. Po otwarciu podglądu wybierz w oknie drukowania opcję „Zapisz jako PDF”.</p></div></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Utwórz PDF</button></div>`,fd=>{const from=fd.get('from'),to=fd.get('to');if(from>to){toast('Data od nie może być późniejsza niż data do');return}closeModal();openPrintablePlan(from,to)})
}
function measurementForm(m){openModal(m?'Edytuj pomiar':'Dodaj pomiar',`<div class="form-grid"><label>Data<input name="date" type="date" required value="${m?.date||new Date().toISOString().slice(0,10)}"></label><label>Masa (kg)<input name="weight" type="number" step="0.1" value="${m?.weight??''}"></label><label>Talia (cm)<input name="waist" type="number" step="0.1" value="${m?.waist??''}"></label><label>Klatka piersiowa (cm)<input name="chest" type="number" step="0.1" value="${m?.chest??''}"></label><label class="full">Notatki<textarea name="notes">${esc(m?.notes||'')}</textarea></label></div><div class="form-actions"><button type="button" class="secondary" data-close>Anuluj</button><button class="primary">Zapisz</button></div>`,async fd=>{const x={id:m?.id||uid(),date:fd.get('date'),weight:num(fd.get('weight'))||null,waist:num(fd.get('waist'))||null,chest:num(fd.get('chest'))||null,notes:fd.get('notes').trim()};m?Object.assign(m,x):state.data.measurements.push(x);closeModal();await save()})}
document.addEventListener('click',async e=>{const t=e.target.closest('button,[data-nav],[data-toggle-shopping],[data-toggle-favorite],[data-duplicate-recipe],[data-add-meal-date]');if(!t)return;if(t.dataset.view)return go(t.dataset.view);if(t.dataset.nav)return go(t.dataset.nav);if(t.dataset.close!==undefined)return closeModal();if(t.dataset.toggleFavorite){const r=recipeById(t.dataset.toggleFavorite);if(r){r.favorite=!r.favorite;await save()}return}if(t.dataset.duplicateRecipe){const r=recipeById(t.dataset.duplicateRecipe);if(r){const copy=structuredClone(r);copy.id=uid();copy.name=`${r.name} – kopia`;copy.favorite=false;state.data.recipes.push(copy);await save();toast('Przepis został zduplikowany')}return}if(t.dataset.addMealDate){return mealForm({date:t.dataset.addMealDate,mealType:t.dataset.addMealType,time:suggestedMealTime(t.dataset.addMealType),portions:1,_new:true})}if(t.dataset.sourceDate)state.copySourceDate=t.dataset.sourceDate;if(t.dataset.action&&actions[t.dataset.action])return actions[t.dataset.action]();if(t.dataset.toggleShopping){const x=(state.data.shoppingList||[]).find(i=>i.id===t.dataset.toggleShopping);if(x){x.purchased=!x.purchased;await save()}return}if(t.dataset.deleteDay){
  const date=t.dataset.deleteDay;
  const dayMeals=state.data.dietPlan.filter(m=>m.date===date);
  if(!dayMeals.length){toast('Ten dzień nie zawiera posiłków');return}
  const label=new Date(date+'T12:00:00').toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long'});
  if(await confirmDialog({title:'Usunąć cały dzień?',message:`${label}\nLiczba posiłków: ${dayMeals.length}`,confirmLabel:'Usuń dzień',danger:true})){
    const before=structuredClone(state.data);
    state.data.dietPlan=state.data.dietPlan.filter(m=>m.date!==date);
    await save();
    toast(`Usunięto cały dzień (${dayMeals.length} posiłków)`,'Cofnij',async()=>{
      const currentUpdatedAt=state.data.updatedAt;
      state.data=before;
      state.data.updatedAt=currentUpdatedAt;
      state.loadedUpdatedAt=currentUpdatedAt;
      await save();
      toast('Usunięcie dnia cofnięte');
    },7000)
  }
  return
}
const map=[['editProduct','products',productForm],['deleteProduct','products'],['editRecipe','recipes',recipeForm],['deleteRecipe','recipes'],['editMeal','dietPlan',mealForm],['deleteMeal','dietPlan'],['editMeasurement','measurements',measurementForm],['deleteMeasurement','measurements'],['editShopping','shoppingList',shoppingForm],['deleteShopping','shoppingList']];for(const [key,arr,fn] of map){const id=t.dataset[key];if(id){const obj=state.data[arr].find(x=>x.id===id);if(key.startsWith('edit'))return fn(obj);if(await confirmDialog({title:'Usunąć element?',message:'Tej operacji można będzie cofnąć przez 7 sekund.',confirmLabel:'Usuń',danger:true})){const before=structuredClone(state.data);state.data[arr]=state.data[arr].filter(x=>x.id!==id);if(arr==='products')state.data.recipes.forEach(r=>r.ingredients=(r.ingredients||[]).filter(i=>i.productId!==id));if(arr==='recipes')state.data.dietPlan=state.data.dietPlan.filter(x=>x.recipeId!==id);await save();toast('Element został usunięty','Cofnij',async()=>{const currentUpdatedAt=state.data.updatedAt;state.data=before;state.data.updatedAt=currentUpdatedAt;state.loadedUpdatedAt=currentUpdatedAt;await save();toast('Usunięcie cofnięte')},7000)}return}}});
const modalClose=$('#modalClose'),modal=$('#modal'),syncBtn=$('#syncBtn'),installBtn=$('#installBtn');if(modalClose)modalClose.onclick=closeModal;if(modal)modal.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#moreSheet')?.addEventListener('click',e=>{if(e.target.id==='moreSheet')closeMore()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#modal').classList.contains('hidden'))closeModal();else closeMore()}});if(syncBtn)syncBtn.onclick=load;
document.addEventListener('input',e=>{if(e.target.matches('.ingredient-product-search')){const select=document.getElementById(e.target.dataset.target);if(!select)return;const current=select.value;select.innerHTML=`<option value="">Wybierz…</option>${productOptions(current,e.target.value)}`;if(current&&[...select.options].some(o=>o.value===current))select.value=current}});
document.addEventListener('change',e=>{if(e.target.matches('.ingredient-product-select')){const p=productById(e.target.value),unit=document.getElementById(e.target.dataset.unitTarget);if(unit)unit.innerHTML=p?unitOptions(p,p.baseUnit):'<option value="g">g</option>'}});
document.addEventListener('change',async e=>{if(e.target.id==='jsonImport'){const file=e.target.files[0];if(!file)return;try{const d=JSON.parse(await file.text());if(!Array.isArray(d.products)||!Array.isArray(d.recipes)||!Array.isArray(d.dietPlan)||!Array.isArray(d.measurements))throw Error('Nieprawidłowy format');d.shoppingList=Array.isArray(d.shoppingList)?d.shoppingList:[];const legacy=num(d.version)<3;d.products=d.products.map(p=>normalizeProductUnits({...p,category:normalizeCategory(p.category,p.name,legacy)}));d.shoppingList=d.shoppingList.map(x=>({...x,category:normalizeCategory(x.category,x.name,legacy)}));d.dietPlan=d.dietPlan.map(m=>({...m,portions:Math.max(0.25,num(m.portions)||1)}));d.version=5;if(await confirmDialog({title:'Zaimportować plik JSON?',message:'Wszystkie aktualne dane zostaną zastąpione zawartością pliku.',confirmLabel:'Importuj'})){state.data=d;await save()}}catch(err){toast('Nieprawidłowy plik JSON')}finally{e.target.value=''}}if(e.target.id==='excelImport'){const file=e.target.files[0];if(!file)return;try{await importExcel(file)}catch(err){console.error(err);toast(`Błąd importu Excel: ${err.message}`)}finally{e.target.value=''}}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;if(installBtn)installBtn.classList.remove('hidden')});if(installBtn)installBtn.onclick=async()=>{if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;installBtn.classList.add('hidden')}};
render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(console.error));
load();
